'use strict';
// Production helper and animation code; controlled rendering, no WebGL.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(process.env.EW_EFFECT_SOURCE||__dirname,'three-vfx-effects.js'),'utf8');
function section(a,b){const i=source.indexOf(a),j=source.indexOf(b,i+a.length);assert.ok(i>=0&&j>i,a);return source.slice(i,j);}
function harness({cap=50,missing=false,vanish=false,particles=true}={}){
 const timers=[],events=[],frames=[],resources=[],warnings=[];let now=0,reads=0,suppressed=false,categoryOff=false;
 class Vector{constructor(x=0,y=0,z=0){this.set(x,y,z);}set(x,y,z){Object.assign(this,{x,y,z});return this;}copy(v){return this.set(v.x,v.y,v.z);}clone(){return new Vector(this.x,this.y,this.z);}sub(v){return this.set(this.x-v.x,this.y-v.y,this.z-v.z);}length(){return Math.hypot(this.x,this.y,this.z);}normalize(){const n=this.length()||1;return this.set(this.x/n,this.y/n,this.z/n);}}
 class Resource{constructor(){this.disposals=0;this.attributes={};resources.push(this);}dispose(){this.disposals++;}clone(){return new Resource();}setAttribute(k,v){this.attributes[k]=v;}getAttribute(k){return this.attributes[k];}setIndex(v){this.index=v;}}
 class Attribute{constructor(array,itemSize){Object.assign(this,{array,itemSize});}setXYZ(i,x,y,z){this.array.set([x,y,z],i*3);}}
 class Quaternion{setFromUnitVectors(a,b){this.a=a;this.b=b;return this;}copy(q){Object.assign(this,q);return this;}}
 class Group{constructor(){this.children=[];this.position=new Vector();this.rotation=new Vector();this.scale=new Vector(1,1,1);this.quaternion=new Quaternion();}add(o){this.children.push(o);o.parent=this;}remove(o){this.children=this.children.filter(c=>c!==o);o.parent=null;}traverse(fn){fn(this);this.children.forEach(c=>c.traverse(fn));}}
 class Mesh extends Group{constructor(geometry,material){super();Object.assign(this,{geometry,material});}}
 const scene=new Group(),texture={dispose(){throw Error('shared texture disposed');}};
 const record=name=>(...args)=>events.push({name,at:now,args:JSON.parse(JSON.stringify(args))});
 const ctx=vm.createContext({Set,Array,Math,Float32Array,console:{warn:(...a)=>warnings.push(a)},performance:{now:()=>now},window:{setTimeout(fn,ms){timers.push({fn,ms,at:now+ms,canceled:false,ran:false});return timers.length;},clearTimeout(id){timers[id-1].canceled=true;}},THREE:{Group,Mesh,Vector3:Vector,Quaternion,BufferGeometry:Resource,BufferAttribute:Attribute,CylinderGeometry:Resource,TubeGeometry:Resource,TorusGeometry:Resource,CatmullRomCurve3:class{constructor(points){this.points=points;}}},_getVFXScene:()=>missing||(vanish&&++reads>1)?null:scene,_worldPos:(x,y)=>({x:x*100,y:20,z:y*100,ts:100}),_worldTorso:(x,y)=>({x:x*100,y:75,z:y*100,ts:100}),_cfg:()=>({tileSize:100}),_sigAuroraCurtainTex:()=>texture,_sigMat:(c,opts)=>Object.assign(new Resource(),{color:{value:c,setHSL(h,s,l){Object.assign(this,{h,s,l});}}},opts),_sigActive:0,_SIG_MAX_ACTIVE:cap,_sigEntries:[],_fxSchedule:fn=>frames.push(fn),_sigClamp01:t=>Math.max(0,Math.min(1,t)),_sigEaseOutCubic:t=>1-(1-t)**3,_canSpawn:()=>particles&&!suppressed,_catOff:()=>categoryOff,_suppressed:()=>suppressed,rn:(a,b)=>(a+b)/2,tilePx:(x,y)=>({x:x*100,y:y*100}),unitSurfaceZ:()=>20,unitZBoost:()=>55,_spawn:record('particle'),_sigPsychedelicTint:record('tint'),_sigKaleidoscope3D:record('kaleidoscope'),_sigNeonGrid3D:record('grid'),_sigFractalTunnel3D:record('tunnel'),_sigSkull3D:record('skull'),_sigSparks:record('sparks'),_sigScreenFlash:record('flash'),_sigShake:record('shake')});
 vm.runInContext(section('    var _fxLifetime','    function rn')+section('    function _sigRun(','    /* full-viewport')+section('    function _sigAuroraCurtain3D(','    /* ── REGEN PULSE')+section('    function _sigBadTrip3D(','    /* ── PSYCHOSIS'),ctx);
 return {ctx,scene,events,resources,timers,warnings,
 fire(kind,opts={}){return kind==='spiral'?ctx._sigSpiralBeam3D(2,3,4,5,opts):ctx[kind==='aurora'?'_sigAuroraCurtain3D':'_sigBadTrip3D'](2,3,opts);},
 tick(ms){now=ms;frames.forEach(f=>f());assert.deepEqual(warnings,[]);},
 advance(ms){for(;;){const t=timers.filter(t=>!t.ran&&!t.canceled&&t.at<=ms).sort((a,b)=>a.at-b.at)[0];if(!t)break;now=t.at;t.ran=true;t.fn();}now=ms;},
 retire(){ctx._fxCancelDelays();[...ctx._sigEntries].forEach(e=>e.finish());},suppress(){suppressed=true;},disable(){categoryOff=true;}
 };
}
for(const kind of ['aurora','spiral']){
 for(const mode of ['cap','vanish'])test(`${kind} ${mode} refusal disposes every instance resource`,()=>{const h=harness(mode==='cap'?{cap:0}:{vanish:true});assert.equal(h.fire(kind),null);assert.equal(h.resources.length,kind==='aurora'?6:14);assert.ok(h.resources.every(r=>r.disposals===1));assert.equal(h.scene.children.length,0);assert.equal(h.ctx._sigActive,0);h.retire();assert.ok(h.resources.every(r=>r.disposals===1));});
 test(`${kind} missing scene allocates nothing`,()=>{const h=harness({missing:true});assert.equal(h.fire(kind),null);assert.equal(h.resources.length,0);assert.equal(h.events.length,0);});
 test(`${kind} retirement after animation ignores old frames and disposes once`,()=>{const h=harness();const e=h.fire(kind);h.tick(120);h.retire();const pos=JSON.stringify(e.group.position);h.tick(5000);e.finish();assert.equal(JSON.stringify(e.group.position),pos);assert.equal(h.scene.children.length,0);assert.ok(h.resources.every(r=>r.disposals===1));});
}
test('aurora updates finite ribbon vertices, colors and fade with custom options',()=>{const h=harness();const e=h.fire('aurora',{curtains:2,ms:1000,radiusPx:120,height:180,baseY:15,opacity:.4,hues:[.2,.7]});assert.equal(h.resources.length,4);assert.equal(e.group.position.y,20);h.tick(140);for(const mesh of e.group.children){const a=mesh.geometry.getAttribute('position');assert.equal(a.needsUpdate,true);assert.ok([...a.array].every(Number.isFinite));assert.equal(a.array[1],15);assert.ok(a.array[4]>15);assert.equal(mesh.frustumCulled,false);assert.ok(mesh.material.opacity>0&&mesh.material.opacity<=.4);assert.ok(Number.isFinite(mesh.material.color.h));}h.tick(900);assert.ok(e.group.children.every(m=>m.material.opacity<.15));h.tick(1000);assert.equal(h.scene.children.length,0);assert.ok(h.resources.every(r=>r.disposals===1));});
test('spiral keeps endpoint placement, extension, particle payloads and cleanup',()=>{const h=harness();const e=h.fire('spiral',{ms:1000,rings:2,strands:1,color:0x123456,coreColor:0xabcdef});assert.equal(h.resources.length,10);assert.deepEqual(JSON.parse(JSON.stringify(e.group.position)),{x:200,y:75,z:300});assert.equal(h.events.length,13);assert.equal(h.events[0].args[0].x,200);assert.equal(h.events[1].args[0].x,400);assert.equal(e.group.children[0].material.color.value,0xabcdef);h.tick(75);const partial=e.group.children[0].scale.y;assert.ok(partial>0&&partial<Math.hypot(200,200));h.tick(200);assert.equal(e.group.children[0].scale.y,Math.hypot(200,200));assert.ok(e.group.children[2].rotation.y>0);h.tick(900);assert.ok(e.group.children[0].material.opacity<.4);h.tick(1000);assert.equal(h.scene.children.length,0);assert.ok(h.resources.every(r=>r.disposals===1));});
test('spiral with particle spawn disabled still registers and cleans its geometry',()=>{const h=harness({particles:false});assert.ok(h.fire('spiral'));assert.equal(h.events.length,0);h.retire();assert.ok(h.resources.every(r=>r.disposals===1));});
test('Bad Trip preserves immediate skull and staggered skull options',()=>{const h=harness();h.fire('trip',{ms:1800});assert.deepEqual(h.timers.map(t=>t.ms),[150,300]);assert.equal(h.events.filter(e=>e.name==='skull').length,1);assert.equal(h.events.find(e=>e.name==='tint').args[0].holdMs,1180);h.advance(149);assert.equal(h.events.filter(e=>e.name==='skull').length,1);h.advance(300);const skulls=h.events.filter(e=>e.name==='skull');assert.deepEqual(skulls.map(e=>[e.at,e.args[2].scale,Math.round(e.args[2].dx),Math.round(e.args[2].dz)]),[[0,.6,-62,-22],[150,.52,58,-34],[300,.68,6,55]]);assert.equal(h.ctx._fxDelays.size,0);});
for(const at of [0,150])test(`Bad Trip retirement at ${at} blocks pending skulls in a fresh lifetime`,()=>{const h=harness();h.fire('trip');h.advance(at);const old=h.timers.filter(t=>!t.ran);h.retire();assert.ok(old.every(t=>t.canceled));h.fire('trip');const n=h.events.length;old.forEach(t=>t.fn());assert.equal(h.events.length,n);h.advance(500);assert.ok(h.events.length>n);});
for(const block of ['suppress','disable'])test(`Bad Trip ${block} preserves initial and delayed gates`,()=>{const h=harness();h[block]();h.fire('trip');assert.equal(h.events.length,0);assert.equal(h.timers.length,0);const live=harness();live.fire('trip');const n=live.events.length;live[block]();live.advance(500);assert.equal(live.events.length,n);});
