// character-creator.test.js — the CHARACTER CREATOR (rev 3 → rev 6, 2026-09-11): the
// v2 appearance data model, the charactercreation/ asset catalogues (rigged
// bases · hair styles · fabrics), the same-origin fallbacks, the rig generator
// and every source site the feature leans on. Asset-level checks run against
// the REAL files in charactercreation/ (skipped when three@0.128 is absent:
// `npm i --no-save three@0.128.0`).
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const read = f => fs.readFileSync(path.join(__dirname, f), 'utf8');
const sprites = read('sprites.js'), renderer = read('three-renderer.js');
const CC = path.join(__dirname, 'charactercreation');
const context = { window: {}, _mkUAL: (folder, prefix, opts) => opts };
vm.createContext(context);
vm.runInContext(sprites.slice(sprites.indexOf('const EW_CHARACTER_ASSET_BASE'), sprites.indexOf('function getRace3DModel')), context);
const normalize = context.normalizeCharacterAppearance;
const HAIR_IDS = context.window.EW_HAIR_STYLES.map(s => s.id);
const RENDER_BLOCK = [renderer.indexOf('     *  CHARACTER CREATOR RUNTIME'), renderer.indexOf('    function _cvResolveDef(')];
// The rigged bases + per-style hair GLBs are GENERATED by `node character-rig.js`
// (CI runs it before npm test). A checkout without them skips the on-disk checks
// instead of failing — the skip message says exactly what to run.
const haveGenerated = ['male', 'female'].every(g => fs.existsSync(path.join(CC, 'Meshy_AI_human_body_base_mesh_' + g + '_rigged.glb')))
    && HAIR_IDS.every(id => fs.existsSync(path.join(CC, 'hair', id + '.glb')));
const GENERATED_SKIP = haveGenerated ? false : 'generated creator assets missing — run `node character-rig.js` (rigs the bases, splits the hair pack)';

test('appearance data clamps values, allowlists every id, upgrades v1 and rejects future versions', () => {
    assert.equal(normalize(null), null);
    assert.equal(normalize([]), null);
    assert.equal(normalize({ version: 3 }), null);
    const a = normalize({ height: 50, width: -2, nose: NaN, jaw: Infinity, skin: 'url(evil)', hair: 'url', model: 'https://evil', waist: '1',
        topFabric: '../../server.js', bottomFabric: 'denim', beard: 'x', outfit: 'suit', bottoms: 'kilt', eyeColor: '#ABCDEF', brows: 9 });
    assert.equal(a.version, 2);
    assert.equal(a.height, 1.15); assert.equal(a.width, 0.85);
    assert.equal(a.nose, 0); assert.equal(a.jaw, 0); assert.equal(a.waist, 0); assert.equal(a.brows, 1);
    assert.equal(a.skin, '#b98362'); assert.equal(a.hair, 'hair003'); assert.equal(a.model, undefined);
    assert.equal(a.topFabric, 'cotton'); assert.equal(a.bottomFabric, 'denim'); assert.equal(a.beard, 'none');
    assert.equal(a.outfit, 'suit'); assert.equal(a.bottoms, 'trousers'); assert.equal(a.eyeColor, '#abcdef');
    assert.equal(normalize({ skin: ['#ffaa00'] }).skin, '#b98362');
    // v1 saves (2026-09-10 procedural shells) keep their meaning
    assert.equal(normalize({ version: 1, hair: 'crop' }).hair, 'hair003');
    assert.equal(normalize({ version: 1, hair: 'crest' }).hair, 'hair000');
    assert.equal(normalize({ version: 1, hair: 'bald' }).hair, 'bald');
    for (const id of HAIR_IDS) assert.equal(normalize({ hair: id }).hair, id);
    // rev 7: the v1 / rev 6 `jacket` TOP is the outer layer over a tee; every layer has a fabric + a tint + a default
    const j = normalize({ outfit: 'jacket' });
    assert.equal(j.outfit, 'tee'); assert.equal(j.outer, 'jacket');
    assert.equal(normalize({ outfit: 'jacket', outer: 'coat' }).outer, 'coat');
    assert.equal(normalize({ outer: 'cape', feet: 'wings', gloves: 'x', belt: 'y', bottoms: 'kilt' }).outer, 'none');
    assert.equal(a.feet, 'sneakers'); assert.equal(a.gloves, 'none'); assert.equal(a.belt, 'none');
    for (const layer of context.window.EW_APPEARANCE_LAYERS) {
        assert.ok(context.window.EW_APPEARANCE_ENUMS[layer.fabric], layer.id + ' has a fabric enum');
        assert.ok(context.window.EW_APPEARANCE_COLORS[layer.color], layer.id + ' has a tint default');
        assert.match(a[layer.color], /^#[0-9a-f]{6}$/); assert.ok(context.window.EW_FABRICS[a[layer.fabric]], layer.id + ' fabric defaults to a catalogue key');
    }
    assert.equal(normalize({ bottoms: 'longskirt', feet: 'highboots', gloves: 'longgloves', belt: 'belt', outer: 'vest', outerColor: '#ABCDEF' }).outerColor, '#abcdef');
    assert.deepEqual(JSON.parse(JSON.stringify(normalize(a))), JSON.parse(JSON.stringify(a)));
    // the randomiser only ever produces legal looks
    let seed = 7; const rng = () => { seed = (seed * 9301 + 49297) % 233280; return seed / 233280; };
    for (let i = 0; i < 40; i++) { const r = context.window.randomCharacterAppearance(rng); assert.deepEqual(normalize(r), r); }
});

test('custom bases are opt-in for humans; every creator asset has exactly one allowlisted fallback', () => {
    assert.equal(context.getCharacterAppearanceModel('fairy', 'male', {}), null);
    assert.equal(context.getCharacterAppearanceModel('homosapien', 'male', null), null);
    for (const gender of ['male', 'female']) {
        const def = context.getCharacterAppearanceModel('homosapien', gender, { height: 1.1 });
        assert.equal(def.heightRatio, 1.1); assert.equal(def.creatorBase, true);
        assert.match(def.model, new RegExp('/Assets/Models/charactercreation/Meshy_AI_human_body_base_mesh_' + gender + '_rigged\\.glb\\?ewcors=1$'));
        assert.equal(context.getCharacterModelFallback(def.model), '/api/character-model/' + gender);
    }
    for (const id of HAIR_IDS) {
        const url = context.window.getHairStyleUrl(id);
        assert.match(url, new RegExp('/charactercreation/hair/' + id + '\\.glb\\?ewcors=1$'));
        assert.equal(context.getCharacterModelFallback(url), '/api/character-model/hair/' + id);
    }
    assert.equal(context.window.getHairStyleUrl('bald'), null); assert.equal(context.window.getHairStyleUrl('hair999'), null);
    for (const key of Object.keys(context.window.EW_FABRICS)) {
        const url = context.window.getFabricTextureUrl(key);
        if (!context.window.EW_FABRICS[key].file) { assert.equal(url, null); continue; }
        assert.match(url, /\/charactercreation\/clothingtextures\/[a-z-]+_basecolor\.png\?ewcors=1$/);
        assert.equal(context.getCharacterModelFallback(url), '/api/character-model/fabric/' + key);
    }
    assert.equal(context.getCharacterModelFallback('https://evil.example/a.glb'), null);
    const assets = context.window.getCharacterAppearanceAssets({ hair: 'hair010', topFabric: 'denim', bottomFabric: 'denim', outerFabric: 'plain', feetFabric: 'denim', glovesFabric: 'plain', beltFabric: 'plain' });
    assert.equal(assets.hair, context.window.getHairStyleUrl('hair010'));
    // (values cross the vm realm — compare by content, not prototype)
    assert.deepEqual([...assets.fabrics], [context.window.getFabricTextureUrl('denim')]);
    assert.equal(JSON.stringify(context.window.getCharacterAppearanceAssets({ hair: 'bald', topFabric: 'plain', bottomFabric: 'plain', outerFabric: 'plain', feetFabric: 'plain', glovesFabric: 'plain', beltFabric: 'plain' })), JSON.stringify({ hair: null, fabrics: [] }));
    // rev 7: the outer layer's / the feet's fabrics warm too
    const assets2 = context.window.getCharacterAppearanceAssets({ topFabric: 'plain', bottomFabric: 'plain', outerFabric: 'wool', feetFabric: 'leather', glovesFabric: 'plain', beltFabric: 'plain' });
    assert.deepEqual([...assets2.fabrics].sort(), [context.window.getFabricTextureUrl('leather'), context.window.getFabricTextureUrl('wool')].sort());
});

// GLB header reader (no deps) — the catalogue must match the files on disk.
function glbJson(file) {
    const buf = fs.readFileSync(file);
    assert.equal(buf.readUInt32LE(0), 0x46546c67, file + ' is a GLB');
    return JSON.parse(buf.slice(20, 20 + buf.readUInt32LE(12)).toString('utf8'));
}
test('the catalogues match charactercreation/ on disk: rigged bases, one GLB per hair style, one tile per fabric', { skip: GENERATED_SKIP }, () => {
    for (const gender of ['male', 'female']) {
        const j = glbJson(path.join(CC, 'Meshy_AI_human_body_base_mesh_' + gender + '_rigged.glb'));
        assert.equal(j.skins.length, 1); assert.equal(j.skins[0].joints.length, 24);
        const names = j.skins[0].joints.map(i => j.nodes[i].name);
        for (const b of ['Hips', 'Spine', 'Head', 'LeftArm', 'RightUpLeg']) assert.ok(names.includes(b), gender + ' rig has ' + b);
        const prim = j.meshes[0].primitives[0];
        for (const attr of ['POSITION', 'NORMAL', 'TEXCOORD_0', 'JOINTS_0', 'WEIGHTS_0']) assert.ok(prim.attributes[attr] != null, gender + ' has ' + attr);
        assert.ok(j.accessors[prim.attributes.POSITION].count > 15000, 'the high-resolution base, not the old export');
        assert.ok(j.animations && j.animations.length >= 1);
        assert.equal(j.asset.extras.ewCharacterRig.source, 'Meshy_AI_human_body_base_mesh_' + gender + '.glb');
    }
    for (const id of HAIR_IDS) {
        const j = glbJson(path.join(CC, 'hair', id + '.glb'));
        assert.equal(j.asset.extras.ewHair.id, id);
        assert.ok(j.asset.extras.ewHair.parts.includes('scalp'), id + ' carries its scalp cap');
        assert.ok(j.nodes.some(n => n.extras && n.extras.ewPart === 'scalp'));
        assert.ok(j.images.length >= 2 && j.images.every(im => im.bufferView != null), id + ' embeds its textures');
        assert.equal(j.skins, undefined, id + ' is static (the runtime skins it to the Head bone)');
    }
    for (const key of Object.keys(context.window.EW_FABRICS)) {
        const f = context.window.EW_FABRICS[key];
        if (!f.file) continue;
        const file = path.join(CC, 'clothingtextures', f.file);
        assert.ok(fs.existsSync(file), key + ' tile exists');
        const b = fs.readFileSync(file);
        assert.equal(b.readUInt32BE(16), 1024, key + ' is 1024 wide');
        assert.ok(f.repeat > 0 && f.rough >= 0 && f.rough <= 1);
    }
});

test('every fabric tile in the catalogue is in charactercreation/clothingtextures and the unrigged bases are never wired', () => {
    for (const key of Object.keys(context.window.EW_FABRICS)) {
        const f = context.window.EW_FABRICS[key];
        if (!f.file) continue;
        assert.ok(fs.existsSync(path.join(CC, 'clothingtextures', f.file)), key + ' tile exists');
        assert.ok(f.repeat > 0 && f.rough >= 0 && f.rough <= 1);
    }
    for (const g of ['male', 'female']) assert.ok(fs.existsSync(path.join(CC, 'Meshy_AI_human_body_base_mesh_' + g + '.glb')), g + ' unrigged source present for character-rig.js');
    // the unrigged uploads are never wired (no skeleton)
    assert.ok(!sprites.includes("base_mesh_' + gender + '.glb"));
});

test('identity resolution preserves a sanitized human appearance and ignores it on other races', () => {
    const s = read('state.js');
    const c = { normalizeCharacterAppearance: normalize, getArchetypeForJob: () => ({}), normalizeRaceKey: r => r,
        getRaceProfile: () => ({ faction: 'time', types: ['human'] }), getAvailableGendersForRace: () => ['male', 'female'],
        getTerrainPreferenceForRace: () => 'none', randInt: () => 0 };
    vm.createContext(c);
    vm.runInContext(s.slice(s.indexOf('        function resolveIdentityForBuild('), s.indexOf('        function randomizeIdentity(')), c);
    const a = c.resolveIdentityForBuild('Freelancer', { race: 'homosapien', gender: 'female', appearance: { waist: 0.5, hair: 'hair014' } });
    assert.equal(a.appearance.waist, 0.5); assert.equal(a.appearance.hair, 'hair014'); assert.equal(a.gender, 'female');
    assert.equal(c.resolveIdentityForBuild('Freelancer', { race: 'fairy', appearance: {} }).appearance, null);
});

test('creator appearances survive team save/load, unit creation and the existing online transport', () => {
    const pb = read('party-builder.js'), map = read('map.js'), net = read('online.js');
    assert.match(pb, /appearance: window\.normalizeCharacterAppearance\?\.\(mt\.appearance\)/);
    assert.match(pb, /st\.partyMeta\[player\]\[i\]\.appearance = window\.normalizeCharacterAppearance\?\.\(s\.appearance\)/);
    assert.match(map, /appearance: identity\.appearance \|\| null/);
    assert.match(renderer, /getRace3DModel\(unit\.race, unit\.gender \|\| 'male', unit\.appearance\)/);
    assert.match(renderer, /_rig\.appearanceKey !== appearanceKey/);
    assert.match(net, /meta: st\.partyMeta \? st\.partyMeta\[2\] : null/);
    const serializer = net.slice(net.indexOf('function _serializeState('), net.indexOf('function _unbox('));
    assert.ok(!/appearance:\s*1/.test(serializer));
    assert.match(pb, /if \(isWaitingOnline \|\| unitRace !== 'homosapien'\) return/);
});

test('the builder panel, the renderer and the CSS carry the rev 3 sites', () => {
    const pb = read('party-builder.js'), css = read('styles-base.css');
    for (const s of ['ccFabricTiles', 'pb-hair-tile', 'pb-fabric-tile', 'randomCharacterAppearance', "ccSlider('eyeSize'", "ccSlider('brows'", "ccColorRow('eyeColor'", "ccColorRow('lipColor'",
        "ccChoice('beard'", "ccChoice('bottoms'", 'EWCharViewer.fabricThumb', 'USE ORIGINAL MODEL', 'FACE CLOSE-UP',
        // rev 7: the layer rows (style · fabric · tint each)
        "ccLayer('Outer layer', 'outer', 'EW_OUTER_STYLES', 'outerFabric', 'outerColor')", "ccLayer('Feet', 'feet', 'EW_FEET_STYLES', 'feetFabric', 'feetColor')",
        "ccLayer('Gloves', 'gloves', 'EW_GLOVE_STYLES', 'glovesFabric', 'glovesColor')", "ccLayer('Belt', 'belt', 'EW_BELT_STYLES', 'beltFabric', 'beltColor')", "window.EW_BOTTOM_STYLES"]) assert.ok(pb.includes(s), 'party-builder has ' + s);
    for (const s of ['.pb-cc-tile', '.pb-fabric-tile', '.pb-hair-tile', '.pb-creator-grid', '.pb-creator-colorrow']) assert.ok(css.includes(s), 'css has ' + s);
    const block = renderer.slice(RENDER_BLOCK[0], RENDER_BLOCK[1]);
    for (const s of ['function _ccBakeSkin', 'function _ccFaceLandmarks', 'function _ccLoadFabric', 'function _ccHairTexture', 'function _ccLoadHair', 'function _ccWarmAssets',
        'function _createAppearanceRig', 'mesh._ew_noTwin = true', 'RepeatWrapping', 'flipY = false',
        // rev 5: the face read off the mesh, the skull map under the hair, the cloth frame's UVs, the scalp under the hair
        'function _ccFaceLandmarks(q, nz, ids)', '_ccFaceLandmarks(q, nz, ids)', 'function buildSkullMap', 'function skullRadius', 'part.skullMap = buildSkullMap(',
        'function clothRegion(', 'function clothUvOf(', 'function fixClothUv(', 'function emitClothTri(', "var scalpOn = a.hair && a.hair !== 'bald'",
        // rev 7: the geometric arm, the strap paths, the panels, the layers, the lathe, the sole, the buckle
        'function armMask(part, q)', 'function strapPath(part, S, ease)', 'function pathDist(path, q)', 'function panelCut(P, sx)', 'function sleevelessCut(part, T)', 'function bikiniCut(part, T)',
        'function bottomCuts(part, B, zc)', 'function feetCuts(part, F)', 'function gloveCuts(part, G)', 'function beltCuts()', 'function buildLathe(opts, b, shade, nBase)', 'function buildSole(b, side, F)', 'function buildBuckle(b)',
        'var CC_LAYER_NAMES', 'var CC_OUTER = {', 'var CC_BOTTOMS = {', 'var CC_FEET = {', 'var CC_GLOVES = {', 'part.armR = { r: aR, step: aStep }']) assert.ok(block.includes(s), 'renderer block has ' + s);
    // the painter reads the MEASURED table, never the constant one; a bald ↔ hair flip repaints
    assert.match(block, /var F = lm\.F \|\| CC_FACE/);
    assert.match(block, /a\.hair === 'bald' \? 'bald' : 'hair'\]\.join/);
    // the garments' UVs are the cloth frame's (metres), the face shell's its cylinder, the body the atlas
    assert.match(block, /writeGeometry\(mesh\.geometry, b, n, L\.uv \|\| CUV, si, sw\)/);
    // the board keeps the creator's surface flags when it swaps materials, skips twins for hair, warms hair + fabrics at match start
    assert.match(renderer, /if \(sm\.alphaTest\) lm\.alphaTest = sm\.alphaTest;/);
    assert.match(renderer, /if \(n\.isMesh && !n\._ew_silhouette && !n\._ew_noTwin\) _silTargets\.push\(n\);/);
    assert.match(renderer, /var as = getCharacterAppearanceAssets\(u\.appearance\);/);
    assert.match(renderer, /fabricUrls\.forEach\(function \(fu\) \{ _ccLoadFabric\(fu, true/);
    assert.match(renderer, /v\.appearancePending = appearance;/);
    assert.match(renderer, /fabricThumb: function \(key, cb\)/);
    // tints ride vertex colours (never material.color — the board's Lambert copy drops it)
    assert.ok(!/material\.color\.set\(a\.(top|bottom|hair)Color/.test(block));
});

test('rev 6 / rev 7 — every catalogue id has a cut, the builder lists the catalogues, the arm is geometric, straps are capsules', () => {
    const block = renderer.slice(RENDER_BLOCK[0], RENDER_BLOCK[1]);
    const tops = block.slice(block.indexOf('var CC_TOPS = {'), block.indexOf('function _ccTopDef('));
    const ids = context.window.EW_OUTFIT_STYLES.map(o => o.id);
    assert.deepEqual(context.window.EW_APPEARANCE_ENUMS.outfit, ids, 'the enum is the catalogue');
    assert.ok(ids.includes('suit') && ids.includes('tee') && ids.includes('tank'), 'the v1 ids survive (saves carry them)');
    for (const id of ids) if (id !== 'none') assert.ok(new RegExp('\\n\\s+' + id + ':\\s*\\{').test(tops), 'CC_TOPS row for ' + id);   // rev 10: 'none' = topless, no row
    assert.ok(new Set(context.window.EW_OUTFIT_STYLES.map(o => o.label)).size === ids.length, 'labels are distinct');
    // sleeved tops end along the arm's polyline, never on an x-plane; sleeveless ones (rev 7) remove the arm by the
    // measured capsule + the hand sphere and wear straps as capsules round a path sampled on the shoulder
    assert.ok(/Math\.max\(len - A\.along, A\.perp - gate\), wristPlane - A\.past/.test(block), 'the sleeve is cut square across the arm and never past the wrist plane (rev 9)');
    assert.ok(/cuts\.push\(function \(q\) \{ return -armMask\(part, q\); \}\)/.test(block), 'sleeveless tops remove the geometric arm');
    assert.ok(!/\(0\.5 - q\[3\]\) \* 0\.05/.test(block), 'the rev 6 weight-isoline arm is gone');
    assert.ok(/var s = hw - pathDist\(straps, q\)/.test(block), 'straps are capsules round the sampled path');
    assert.ok(!/sleeve - Math\.abs\(q\[0\]\)/.test(block), 'the rev 5 x-plane sleeve is gone');
    // every sleeveless top has both panels (or a bikini) and, if it has straps, xIn clear of the neck base
    const cc = {}; vm.runInContext(block.slice(block.indexOf('var CC_TANK_FRONT'), block.indexOf("/* The pack's hair diffuse")), vm.createContext(cc));
    for (const id of ids) { const T = cc.CC_TOPS[id]; if (T && T.sleeve == null && !T.bikini) { assert.ok(T.front && T.back, id + ' has panels'); if (T.straps) assert.ok(T.front.xIn >= 0.056 && T.straps.w > 0.01, id + ' straps clear the neck base'); } }
    // rev 7: every catalogue id of the other layers has a row (none = nothing worn)
    for (const [cat, table] of [['EW_BOTTOM_STYLES', 'CC_BOTTOMS'], ['EW_OUTER_STYLES', 'CC_OUTER'], ['EW_FEET_STYLES', 'CC_FEET'], ['EW_GLOVE_STYLES', 'CC_GLOVES']]) {
        const catIds = context.window[cat].map(o => o.id).filter(x => x !== 'none');
        assert.equal(JSON.stringify([...context.window.EW_APPEARANCE_ENUMS[{ EW_BOTTOM_STYLES: 'bottoms', EW_OUTER_STYLES: 'outer', EW_FEET_STYLES: 'feet', EW_GLOVE_STYLES: 'gloves' }[cat]]]), JSON.stringify([...context.window[cat].map(o => o.id)]), cat + ' is the enum');
        for (const id of catIds) assert.ok(cc[table][id], table + ' row for ' + id);
        for (const id of Object.keys(cc[table])) assert.ok(catIds.includes(id), table + ' row ' + id + ' is in the catalogue');
    }
    // (arrays cross vm realms — compare by content)
    assert.equal(JSON.stringify(Object.keys(cc.CC_TOPS).sort()), JSON.stringify(ids.filter(x => x !== 'none').sort()), 'CC_TOPS is exactly the catalogue (minus topless)');
    assert.ok(!ids.includes('jacket'), 'the jacket is an outer layer now');
    assert.equal(JSON.stringify([...cc.CC_LAYER_NAMES]), JSON.stringify(['body', 'top', 'bottom', 'face', 'outer', 'feet', 'gloves', 'belt', 'skirt', 'buckle', 'trim', 'tie', 'glasses', 'top2', 'bottom2']));   // rev 9: + trim · tie · glasses; rev 10: + the extra layers
    assert.ok(/RN\[i3\] \* dn/.test(block), 'the cloth relaxation moves along the normal only');
    assert.ok(/v\.on \|= \(bit \|\| 0\)/.test(block) && /if \(!\(v\.on & w\.on\)\)|var shared = v\.on & w\.on/.test(block), 'rims are found by the cut masks');
    const pb = read('party-builder.js');
    assert.ok(/ccChoice\('outfit', \(window\.EW_OUTFIT_STYLES/.test(pb), 'the builder lists the catalogue');
});

test('same-origin fallback serves only the rigged bases, hairNNN styles and lowercase fabric keys', () => {
    const s = read('server.js'), start = s.indexOf('// CHARACTER CREATOR same-origin fallback');
    const calls = [];
    const c = { __dirname, path, limitRead: () => {}, app: { get: (...args) => calls.push(args) } };
    vm.createContext(c); vm.runInContext(s.slice(start, s.indexOf('// Serve ONLY', start)), c);
    const routes = Object.fromEntries(calls.map(a => [a[0], a[2]]));
    assert.deepEqual(Object.keys(routes).sort(), ['/api/character-model/:gender', '/api/character-model/fabric/:key', '/api/character-model/hair/:id']);
    const run = (route, params) => { let status, file; const res = { sendStatus: n => status = n, type: () => {}, sendFile: f => file = f }; routes[route]({ params }, res); return { status, file }; };
    for (const gender of ['male', 'female']) assert.equal(run('/api/character-model/:gender', { gender }).file, path.join(CC, 'Meshy_AI_human_body_base_mesh_' + gender + '_rigged.glb'));
    for (const bad of ['../server.js', 'other', 'MALE']) assert.deepEqual(run('/api/character-model/:gender', { gender: bad }), { status: 404, file: undefined });
    assert.equal(run('/api/character-model/hair/:id', { id: 'hair010' }).file, path.join(CC, 'hair', 'hair010.glb'));
    for (const bad of ['hair', 'hair10', 'hair0100', '../x', 'HAIR000', 'hair00x']) assert.deepEqual(run('/api/character-model/hair/:id', { id: bad }), { status: 404, file: undefined });
    assert.equal(run('/api/character-model/fabric/:key', { key: 'ribbed-knit' }).file, path.join(CC, 'clothingtextures', 'ribbed-knit_basecolor.png'));
    for (const bad of ['../x', 'Denim', 'denim_basecolor.png', 'a-b-c', 'a--b', '']) assert.deepEqual(run('/api/character-model/fabric/:key', { key: bad }), { status: 404, file: undefined });
});

// Optional asset-level validation: npm install --no-save three@0.128.0.
// Uses the real r128 CPU skinning math, with no browser or gameplay automation.
let THREE;
try { THREE = require('three'); } catch (_) {}
const haveModels = fs.existsSync(path.join(CC, 'Meshy_AI_human_body_base_mesh_male_rigged.glb')) && fs.existsSync(path.join(CC, 'hair', 'hair003.glb'));
test('both rigged bases dress, fit the hair to the skull and stay finite across outfits and shape limits', { skip: !THREE || !haveModels }, async () => {
    const c = { THREE, console, TextDecoder, URL, Blob, setTimeout, clearTimeout, performance, normalizeCharacterAppearance: normalize,
        getHairStyleUrl: context.window.getHairStyleUrl, getFabricTextureUrl: context.window.getFabricTextureUrl, getCharacterAppearanceAssets: context.window.getCharacterAppearanceAssets,
        getCharacterModelFallback: context.getCharacterModelFallback, EW_FABRICS: context.window.EW_FABRICS, _unitGlbCache: {} };
    c.self = c; c.window = c;
    c._loadUnitGLB = (url, cb) => { const e = c._unitGlbCache[url]; if (e && e.root) cb(e); };
    vm.createContext(c);
    vm.runInContext(fs.readFileSync(require.resolve('three/examples/js/loaders/GLTFLoader.js'), 'utf8'), c);
    vm.runInContext(fs.readFileSync(require.resolve('three/examples/js/utils/SkeletonUtils.js'), 'utf8'), c);
    vm.runInContext(renderer.slice(renderer.indexOf('    /* ══════════════════════════════════════════════════════════════════\n     *  CHARACTER CREATOR RUNTIME'), RENDER_BLOCK[1]), c);
    // Node has no <img>: embedded hair textures become empty Textures (geometry is what we test)
    const origLoad = THREE.TextureLoader.prototype.load;
    THREE.TextureLoader.prototype.load = function (url, onLoad) { const t = new THREE.Texture(); if (onLoad) setTimeout(() => onLoad(t), 0); return t; };
    const load = f => new Promise((ok, fail) => { const b = fs.readFileSync(f); new THREE.GLTFLoader().parse(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength), '', ok, fail); });
    try {
        // rev 5: the face is READ OFF each base — the two differ by a centimetre at the mouth and the nose
        const faces = {};
        for (const gender of ['male', 'female']) {
            const gltf = await load(path.join(CC, 'Meshy_AI_human_body_base_mesh_' + gender + '_rigged.glb'));
            let m; gltf.scene.traverse(n => { if (n.isSkinnedMesh) m = m || n; });
            const pos = m.geometry.attributes.position, nr = m.geometry.attributes.normal, box = new THREE.Box3().setFromBufferAttribute(pos), H = box.max.y - box.min.y;
            const q = [], nz = [];
            for (let i = 0; i < pos.count; i++) { q.push([pos.getX(i) / H, (pos.getY(i) - box.min.y) / H, pos.getZ(i) / H]); nz.push(nr.getZ(i)); }
            faces[gender] = c._ccFaceLandmarks(q, nz, Array.from(m.geometry.index.array));
            const F = faces[gender].F;
            assert.equal(faces[gender].measured, true, gender + ' face measured off the mesh');
            assert.ok(F.mouthT > F.chinT + 0.015 && F.mouthT < F.subnasale - 0.006 && F.subnasale < F.noseT, gender + ' mouth between chin and nose: ' + JSON.stringify(F));
            assert.ok(faces[gender].eyes[1].t > F.noseT + 0.012 && faces[gender].eyes[1].t < F.browT - 0.007, gender + ' eyes between the nose tip and the brow ridge');
            assert.ok(F.browT - faces[gender].eyes[1].t <= 0.013 + 1e-9, gender + ' brow within 13 mm(q) of the eye');
            assert.ok(F.mouthHalfW >= 0.012 && F.mouthHalfW <= 0.017 && F.upperLip >= 0.0035 && F.lowerLip >= 0.004);
        }
        assert.ok(Math.abs(faces.male.F.mouthT - 0.8985) < 0.0025, 'male mouth line on the mesh crease (' + faces.male.F.mouthT + ')');
        assert.ok(Math.abs(faces.female.F.mouthT - 0.8915) < 0.0025, 'female mouth line on the mesh crease (' + faces.female.F.mouthT + ')');
        assert.ok(faces.male.F.noseT - faces.female.F.noseT > 0.003, 'the bases do not share a nose');
        const hairUrl = context.window.getHairStyleUrl('hair003');
        const hg = await load(path.join(CC, 'hair', 'hair003.glb'));
        hg.scene.traverse(n => { if (n.isMesh) n.geometry._ew_shared = true; });
        c._unitGlbCache[hairUrl] = { root: hg.scene, clips: [], loading: false, failed: false, cbs: [] };
        for (const gender of ['male', 'female']) {
            const gltf = await load(path.join(CC, 'Meshy_AI_human_body_base_mesh_' + gender + '_rigged.glb'));
            let original; gltf.scene.traverse(n => { if (n.isSkinnedMesh) original = n; });
            const before = Array.from(original.geometry.attributes.position.array);
            const clone = THREE.SkeletonUtils.clone(gltf.scene), other = THREE.SkeletonUtils.clone(gltf.scene);
            let untouched; other.traverse(n => { if (n.isSkinnedMesh) untouched = n; });
            const rig = c._createAppearanceRig(clone, { hair: 'hair003' }, true);
            const skinned = () => { const out = []; clone.traverse(n => { if (n.isSkinnedMesh && n.parent) out.push(n); }); return out; };
            let bodies = skinned();
            assert.equal(bodies.filter(n => !/hair/.test(n.name)).length, 15, 'body + top + bottom + face + outer + feet + gloves + belt + skirt + buckle (rev 7) + trim + tie + glasses (rev 9) + top2 + bottom2 (rev 10)');
            const shellNames = bodies.filter(n => /EWCreator_/.test(n.name) && !/hair/.test(n.name)).map(n => n.name.replace('EWCreator_', '')).sort();
            assert.deepEqual(shellNames, ['belt', 'bottom', 'buckle', 'face', 'feet', 'gloves', 'outer', 'skirt', 'top', 'trim', 'tie', 'glasses', 'top2', 'bottom2'].sort());
            const hairMeshes = bodies.filter(n => /EWCreator_hair/.test(n.name));
            assert.ok(hairMeshes.length >= 2, 'hair parts skinned in');
            const body = bodies.find(n => !/EWCreator/.test(n.name));
            body.geometry.computeBoundingBox();
            const headTop = body.geometry.boundingBox.max.y;
            // rev 5: every hair vertex stands OFF the skull (the collision pass) — sample the skull as the body's head vertices
            const bodyPos = body.geometry.attributes.position, headPts = [];
            body.geometry.computeBoundingBox(); const bbb = body.geometry.boundingBox, Hb = bbb.max.y - bbb.min.y;
            for (let i = 0; i < bodyPos.count; i++) if ((bodyPos.getY(i) - bbb.min.y) / Hb > 0.9) headPts.push([bodyPos.getX(i), bodyPos.getY(i), bodyPos.getZ(i)]);
            const scalp = hairMeshes.find(n => /scalp/.test(n.name));
            assert.ok(scalp, 'the style has a scalp cap');
            { const sp = scalp.geometry.attributes.position; let inside = 0, tested = 0;
              for (let i = 0; i < sp.count; i += 3) {
                  const y = sp.getY(i); if ((y - bbb.min.y) / Hb < 0.94) continue;   // the cap's crown only (its rim is tucked / conformed elsewhere)
                  tested++;
                  const px = sp.getX(i), pz = sp.getZ(i);
                  // inside = some head vertex within 4 mm laterally lies FURTHER out than the cap in its own direction
                  const cx = 0, cz = 0; const r = Math.hypot(px - cx, pz - cz);
                  for (const h of headPts) { if (Math.abs(h[1] - y) > 0.004) continue; const hr = Math.hypot(h[0] - cx, h[2] - cz); const ang = Math.abs(Math.atan2(h[0] - cx, h[2] - cz) - Math.atan2(px - cx, pz - cz)); if (ang < 0.05 && hr > r + 0.006) { inside++; break; } }
              }
              assert.ok(tested > 20, 'sampled the crown of the cap');
              assert.ok(inside / tested < 0.03, gender + ' scalp cap sits outside the skull (' + inside + '/' + tested + ' inside)'); }
            for (const hm of hairMeshes) {
                hm.geometry.computeBoundingBox();
                const bb = hm.geometry.boundingBox;
                assert.ok(bb.max.y > headTop - 0.02 && bb.max.y < headTop + 0.035, gender + ' hair crown sits on the skull top (' + bb.max.y.toFixed(3) + ' vs ' + headTop.toFixed(3) + ')');
                assert.ok(bb.max.x < 0.2 && bb.min.x > -0.2, 'hair width is head-sized');
                const si = hm.geometry.attributes.skinIndex, headBone = body.skeleton.bones.findIndex(b => b.name === 'Head');
                assert.equal(si.getX(0), headBone, 'hair rides the Head bone');
                assert.equal(hm._ew_noTwin, true);
                assert.ok(hm.material.alphaTest > 0 || /tie/.test(hm.name));
            }
            const EN = context.window.EW_APPEARANCE_ENUMS, cyc = (arr, i) => arr[i % arr.length];
            const cc = {}; { const block = renderer.slice(RENDER_BLOCK[0], RENDER_BLOCK[1]); vm.runInContext(block.slice(block.indexOf('var CC_TANK_FRONT'), block.indexOf("/* The pack's hair diffuse")), vm.createContext(cc)); }
            let step = 0;
            for (const outfit of EN.outfit) for (const sign of [-1, 0, 1]) {
                // rev 7: the other layers cycle through their catalogues alongside (every id is worn at least once per base)
                const bottoms = cyc(EN.bottoms, step), outer = cyc(EN.outer, step), feet = cyc(EN.feet, step), gloves = cyc(EN.gloves, step), belt = cyc(EN.belt, step), neckwear = cyc(EN.neckwear, step), glasses = cyc(EN.glasses, step); step++;
                rig.update({ outfit, bottoms, outer, feet, gloves, belt, neckwear, glasses, hair: sign < 0 ? 'bald' : 'hair003', topFabric: sign ? 'denim' : 'plain', outerFabric: 'wool', width: 1 + sign * .15, chest: sign, waist: sign, hips: sign, head: sign, jaw: sign, cheeks: sign, nose: sign });
                const arm = body.skeleton.bones.find(b => b.name === 'LeftArm'); arm.rotation.z = .4;
                clone.updateMatrixWorld(true);
                bodies = skinned();
                assert.equal(bodies.some(n => /EWCreator_hair/.test(n.name)), sign >= 0, 'bald drops the hair meshes');
                for (const n of bodies) {
                    assert.notEqual(n.geometry, original.geometry);
                    assert.notEqual(n.skeleton, untouched.skeleton);
                    const pos = n.geometry.attributes.position;
                    assert.ok(Array.from(pos.array).every(Number.isFinite));
                    n.skeleton.update();
                    const v = new THREE.Vector3();
                    for (let i = 0; i < pos.count; i += 37) {
                        n.boneTransform(i, v); v.applyMatrix4(n.matrixWorld);
                        assert.ok([v.x, v.y, v.z].every(Number.isFinite));
                        assert.ok(v.length() < 5, 'fitted geometry escaped the metre-scale rig');
                    }
                    const weights = n.geometry.attributes.skinWeight;
                    for (let i = 0; i < weights.count; i += 7) {
                        const sum = weights.getX(i) + weights.getY(i) + weights.getZ(i) + weights.getW(i);
                        assert.ok(Math.abs(sum - 1) < 1e-5, 'cut vertices retain normalized skin weights');
                    }
                    assert.ok(Array.from(n.geometry.index.array).every(i => i < pos.count));
                    assert.ok(n.geometry.attributes.uv && n.geometry.attributes.uv.count === pos.count, 'every shell carries UVs for its texture');
                }
                const top = bodies.find(n => n.name === 'EWCreator_top'), bottom = bodies.find(n => n.name === 'EWCreator_bottom'), skirt = bodies.find(n => n.name === 'EWCreator_skirt');
                const shellOf = nm => bodies.find(n => n.name === 'EWCreator_' + nm);
                const isSkirtBottom = /skirt/.test(bottoms), isDress = /dress|gown/.test(outfit);
                assert.equal(top.geometry.index.count > 0, outfit !== 'none', outfit + ' drew a top (rev 10: topless draws none)');
                assert.equal(bottom.geometry.index.count > 0, !isSkirtBottom, bottoms + ' bottom shell drawn iff it is a cut (' + outfit + ')');
                assert.equal(skirt.geometry.index.count > 0, isDress || isSkirtBottom, 'the lathe is drawn for a dress / gown / skirt (' + outfit + ' + ' + bottoms + ')');
                assert.equal(shellOf('outer').geometry.index.count > 0, outer !== 'none', outer + ' outer shell');
                assert.equal(shellOf('feet').geometry.index.count > 0, feet !== 'none', feet + ' feet shell');
                assert.equal(shellOf('gloves').geometry.index.count > 0, gloves !== 'none', gloves + ' gloves shell');
                assert.equal(shellOf('belt').geometry.index.count > 0, belt === 'belt', belt + ' belt shell');
                assert.equal(shellOf('buckle').geometry.index.count > 0, belt === 'belt', belt + ' buckle');
                for (const nm of ['outer', 'feet', 'gloves', 'belt', 'skirt', 'buckle', 'trim', 'tie', 'glasses']) assert.equal(shellOf(nm).visible, shellOf(nm).geometry.index.count > 0, nm + ' hidden when empty');
                // rev 9: the accessories draw iff worn; the details of a row land in its layer / the trim shell
                assert.equal(shellOf('tie').geometry.index.count > 0, neckwear !== 'none', neckwear + ' neckwear shell');
                assert.equal(shellOf('glasses').geometry.index.count > 0, glasses !== 'none', glasses + ' glasses shell');
                const CO = cc.CC_OUTER[outer], CT = cc.CC_TOPS[outfit], wantsTrim = !!((CO && (CO.buttons || CO.zipTape)) || (CT && CT.placket) || neckwear === 'bowtie');
                assert.equal(shellOf('trim').geometry.index.count > 0, wantsTrim, outer + ' / ' + outfit + ' trim (buttons, zip, placket buttons, a bow knot)');
                assert.equal(top.material.vertexColors, true);
                // rev 5: garment UVs are the cloth frame's, in METRES — v spans the shirt's height, u the arc round the body,
                // and no drawn triangle straddles a seam (every |Δu| within a triangle stays under half a torso turn)
                for (const [gm, minSpan] of [[top, 0.15], [bottom, 0.2]]) {
                    if (gm.geometry.index.count === 0) continue;
                    // rev 10: u runs at the LOCAL radius, so the seam check is on the angle (a full turn ≤ 2π × 0.25 m) — the metre bound loosened to match
                    const uv = gm.geometry.attributes.uv, idx = gm.geometry.index.array; let vmin = Infinity, vmax = -Infinity, worst = 0;
                    for (let i = 0; i < idx.length; i += 3) { const u0 = uv.getX(idx[i]), u1 = uv.getX(idx[i + 1]), u2 = uv.getX(idx[i + 2]); worst = Math.max(worst, Math.max(u0, u1, u2) - Math.min(u0, u1, u2)); for (const k of [idx[i], idx[i + 1], idx[i + 2]]) { const vv = uv.getY(k); if (vv < vmin) vmin = vv; if (vv > vmax) vmax = vv; } }
                    assert.ok(vmax - vmin > (gm === bottom && /briefs|bikini|shortshorts/.test(bottoms) ? 0.05 : minSpan) && vmax - vmin < 2.0, gm.name + ' v runs the garment\'s height in metres (' + (vmax - vmin).toFixed(3) + ', ' + bottoms + ')');
                    assert.ok(worst < Math.PI * 0.15 * 1.05, gm.name + ' no triangle spans the seam (worst Δu ' + worst.toFixed(3) + ')');
                }
            }
            assert.deepEqual(Array.from(original.geometry.attributes.position.array), before, 'the cached base geometry is never edited');
            let disposed = 0; skinned().forEach(n => n.geometry.addEventListener('dispose', () => disposed++));
            const count = skinned().length;
            rig.dispose(); assert.equal(disposed, count);
        }
    } finally { THREE.TextureLoader.prototype.load = origLoad; }
});

test('R2 load failure retries only the allowlisted model and settles the existing cache', () => {
    const calls = [], cache = {};
    const root = { traverse: () => {} };
    const c = { console, _unitGlbCache: cache, _skinnedBBox: () => ({}), invalidateUnits: () => {},
        getCharacterModelFallback: context.getCharacterModelFallback,
        THREE: { GLTFLoader: class { load(url, ok, progress, fail) {
            calls.push(url); if (url.startsWith('/api/')) ok({ scene: root, animations: [] }); else fail();
        } } } };
    vm.createContext(c);
    vm.runInContext(renderer.slice(renderer.indexOf('    var _mobileModelJobs'), renderer.indexOf('    /* Match-start preload gate')), c);
    vm.runInContext(renderer.slice(renderer.indexOf('    function _compactMobileModelTextures('), renderer.indexOf('    function _loadMiscModel(')), c);
    const url = context.getCharacterAppearanceModel('homosapien', 'female', {}).model;
    let result; c._loadUnitGLB(url, e => result = e);
    assert.deepEqual(calls, [url, '/api/character-model/female']);
    assert.equal(result.root, root); assert.equal(result.loading, false);
    c._loadUnitGLB(url, e => assert.equal(e, result));
    assert.equal(calls.length, 2, 'second caller should reuse the settled model');
    const hair = context.window.getHairStyleUrl('hair014');
    c._loadUnitGLB(hair, () => {});
    assert.deepEqual(calls.slice(2), [hair, '/api/character-model/hair/hair014']);
});

test('character-rig.js reproduces the rigged bases from the donors (weights transferred, tree kept)', { skip: GENERATED_SKIP }, () => {
    const tool = require('./character-rig.js');
    const donor = tool.readGlb(tool.DONOR('male')), out = tool.readGlb(tool.RIGGED('male'));
    assert.deepEqual(out.json.nodes.map(n => n.name), donor.json.nodes.map(n => n.name), 'the donor node tree is kept verbatim');
    assert.deepEqual(out.json.skins[0].joints, donor.json.skins[0].joints);
    const prim = out.json.meshes[0].primitives[0];
    const w = tool.readAccessor(out, prim.attributes.WEIGHTS_0), j = tool.readAccessor(out, prim.attributes.JOINTS_0), p = tool.readAccessor(out, prim.attributes.POSITION);
    assert.equal(w.length, j.length); assert.equal(w.length / 4, p.length / 3);
    for (let i = 0; i < w.length; i += 4 * 97) { const s = w[i] + w[i + 1] + w[i + 2] + w[i + 3]; assert.ok(Math.abs(s - 1) < 1e-4); for (let k = 0; k < 4; k++) assert.ok(j[i + k] < 24); }
    const acc = out.json.accessors[prim.attributes.POSITION];
    assert.ok(Math.abs((acc.max[1] - acc.min[1]) - 1.7) < 0.01, 'the donor\'s metre-scale bind frame (1.70 m)');
    assert.ok(acc.min[1] > -0.01 && acc.min[1] < 0.01, 'feet on the donor floor');
    // the closest-point routine the transfer rests on
    const q = tool.closestOnTriangle([0.2, 0.2, 1], [0, 0, 0], [1, 0, 0], [0, 1, 0]);
    assert.deepEqual(q.p.map(v => +v.toFixed(6)), [0.2, 0.2, 0]);
    assert.ok(Math.abs(q.bary[0] + q.bary[1] + q.bary[2] - 1) < 1e-9);
    assert.deepEqual(tool.closestOnTriangle([-1, -1, 0], [0, 0, 0], [1, 0, 0], [0, 1, 0]).bary, [1, 0, 0]);
    assert.equal(tool.partKind('Dransvitry\\HunterHairs\\Hair010.mdl_HairTie_HairTie.dmx_MESH'), 'tie');
    assert.equal(tool.partKind('Hair009.mdl_HairUnder_HairUnder.dmx_MESH'), 'under');
    assert.equal(tool.partKind('Hair003.mdl_Scalp01_Scalp01.dmx_MESH'), 'scalp');
    assert.equal(tool.partKind('Hair003.mdl_Hair_Hair.dmx_MESH'), 'hair');
});

/* ── rev 8 (2026-09-13): the outer layer's fixes, THE PRINTS (two colours on every layer), THE MIRROR (Occam's
   Barbershop is the character creator; the officer's look; the ID card's bust) ── */
test('rev 8 — the prints: the catalogue is the enum, every pattern masks 0..1 and tiles, the painter multiplies both colours onto a tile', () => {
    const pats = context.window.EW_PATTERNS.map(p => p.id);
    assert.ok(pats[0] === 'solid' && pats.length >= 10 && new Set(pats).size === pats.length, 'solid first, a dozen distinct ids');
    for (const L of context.window.EW_APPEARANCE_LAYERS) {
        assert.ok(L.pattern && L.color2, L.id + ' carries a pattern + colour-2 key');
        assert.equal(JSON.stringify([...context.window.EW_APPEARANCE_ENUMS[L.pattern]]), JSON.stringify(pats), L.pattern + ' is the catalogue');
        assert.ok(/^#[0-9a-f]{6}$/.test(normalize({})[L.color2]), L.color2 + ' has a default');
        assert.equal(normalize({})[L.pattern], 'solid', 'solid by default');
    }
    assert.equal(normalize({ topPattern: 'bogus' }).topPattern, 'solid', 'an unknown print is solid');
    assert.equal(normalize({ topPattern: 'polka', topColor2: '#ABCDEF' }).topColor2, '#abcdef');
    // the painter, in a sandbox with a stub THREE.Color
    const block = renderer.slice(RENDER_BLOCK[0], RENDER_BLOCK[1]);
    const pc = { THREE: { Color: function (hex) { const n = parseInt(String(hex).slice(1), 16); this.r = ((n >> 16) & 255) / 255; this.g = ((n >> 8) & 255) / 255; this.b = (n & 255) / 255; } }, Math };
    vm.createContext(pc);
    vm.runInContext(block.slice(block.indexOf('var _CC_PATTERN_CELLS'), block.indexOf('/* the printed tile as an instance-owned CanvasTexture')), pc);
    for (const id of pats) {
        let lo = Infinity, hi = -Infinity;
        for (let i = 0; i < 400; i++) { const m = pc._ccPatternMask(id, (i % 20) / 20 + 0.013, Math.floor(i / 20) / 20 + 0.017); assert.ok(m >= 0 && m <= 1 && Number.isFinite(m), id + ' masks 0..1'); lo = Math.min(lo, m); hi = Math.max(hi, m); }
        if (id !== 'solid') assert.ok(hi > lo, id + ' is not flat');
        assert.equal(pc._ccPatternMask(id, 0.3, 0.7), pc._ccPatternMask(id, 1.3, -0.3), id + ' tiles');
    }
    const S = 16, d = new Uint8ClampedArray(S * S * 4).fill(255);
    pc._ccPatternBytes(d, S, 'stripes', '#ff0000', '#0000ff');
    assert.deepEqual([d[0], d[1], d[2]], [0, 0, 255], 'the left half of a stripe cell is colour 2');
    assert.deepEqual([d[(S - 1) * 4], d[(S - 1) * 4 + 1], d[(S - 1) * 4 + 2]], [255, 0, 0], 'the right half is colour 1');
    const w = new Uint8ClampedArray(S * S * 4).fill(128);
    pc._ccPatternBytes(w, S, 'stripes', '#ffffff', '#ffffff');
    assert.ok(w.every((v, i) => i % 4 === 3 || v === 128), 'white × white leaves the tile');
    // the renderer's wiring + the tools + the builder + the CSS
    for (const s of ['function _ccPatternMask(id, u, v)', 'function _ccPatternBytes(d, S, pat, c1, c2, cells)', 'function _ccPatternTexture(fabTex, pat, c1, c2, def, unmanaged, size, cellsMul)', "topPattern', 'topColor2'", 'function layerPrinted(a, keys)', "tint = layerPrinted(a, keys) ? color('#ffffff') : color(a[keys[1]])", "var want = printed ? ('P|'", 'part.patTex[which]']) assert.ok(block.includes(s), 'renderer block has ' + s);
    assert.match(renderer, /patternThumb: function \(fabricKey, pat, c1, c2, cb\)/);
    const pb = read('party-builder.js'), css = read('styles-base.css'), cr = read('creator-render.js');
    for (const s of ['const ccPrint = (fabricKey, colorKey, label)', "ccPrint('topFabric', 'topColor', 'Top')", "ccPrint('bottomFabric', 'bottomColor', 'Bottom')", 'worn ? ccPrint(fabricKey, colorKey, label) : null', 'pb-pattern-tile', 'EWCharViewer.patternThumb', "' colour 2'"]) assert.ok(pb.includes(s), 'party-builder has ' + s);
    assert.ok(css.includes('.pb-pattern-tile') && css.includes('.pb-cc-prints'), 'css has the print tiles');
    assert.ok(cr.includes('c._ccPatternBytes(d, S, pat, c1, c2)'), 'creator-render.js prints through the same painter');
});

test('rev 8 — the outer layer: tapered sleeves, no collar cap, the folded rims, the lathe on the relaxed skin, the shoulder cap', () => {
    const block = renderer.slice(RENDER_BLOCK[0], RENDER_BLOCK[1]);
    const cc = {}; vm.runInContext(block.slice(block.indexOf('var CC_TANK_FRONT'), block.indexOf("/* The pack's hair diffuse")), vm.createContext(cc));
    for (const id of ['jacket', 'blazer', 'coat']) {
        const O = cc.CC_OUTER[id];
        assert.ok(O.sleeveEase != null && O.sleeveEase < O.ease, id + ' tapers its sleeve to the wrist');
        assert.ok(!O.neck.top, id + ' has no collar cap (the cut stays on the 0.852 ridge)');
    }
    assert.ok(cc.CC_OUTER.vest.front.top <= 0.80 && cc.CC_OUTER.vest.straps.w >= 0.04, 'the vest wears the tank heights with wide straps');
    // rev 9: the coat's skirt is the shell itself (no lathe tail — it tore on every posed stance)
    assert.ok(!cc.CC_OUTER.coat.tail && cc.CC_OUTER.coat.hem <= 0.42 && cc.CC_OUTER.coat.hemEase > cc.CC_OUTER.coat.ease && cc.CC_OUTER.coat.hemEaseFrom > cc.CC_OUTER.coat.hem, 'the coat is one shell to mid-thigh at a larger stand-off below the hips');
    for (const s of ['function layerEase(T, extra)', 'part.armFrac = armFrac', 'var lapelRaise = (OUT && OUT.open && OUT.lapel)', 'clothSurface(layerEase(OUT, lapelRaise), true, false)',
        'proj: proj', '(0.45 + 0.55 * kb)', 'var px = R[ii * 3] + NB[ii * 3] * ease * H', 'THE FOLD (rev 8)', "emit([vo, vi, wi, wo], target, 0.92)", 'function skirtShade(tTop, tHem, plain)', 'tTop: OUT.hem + 0.006', 'window.EW_CC_DEBUG_CUTS']) assert.ok(block.includes(s), 'renderer block has ' + s);
    assert.ok(!block.includes('0.848, w: 0.05, top: 0.848'), 'the rev 7 collar cap is gone');
});

test('rev 8 — the mirror: the officer look on the profile, the chair’s look mode, the walker, the card’s bust, the creator screens render', async () => {
    const dj = read('data.js'), mp = read('map.js'), pf = read('profile.js'), pb = read('party-builder.js'), ih = read('index.html'), css = read('styles-base.css');
    for (const s of ['function hqLook(profile)', 'function hqSetLook(profile, look)', "'player', 'vessel', 'agent', 'race', 'look'", "if (rec.mode === 'look') return hqLook(profile) ? { mode: 'look' } : { mode: 'player' };", "case 'look':   return 'YOUR OWN LOOK';", "action: { fn: '_mountReactCreator' }", 'window.hqLook = hqLook;', 'window.hqSetLook = hqSetLook;']) assert.ok(dj.includes(s), 'data.js has ' + s);
    for (const s of ["_mountReactCreator: '_unmountReactCreator'", "_mountReactCreator: 'CHARACTER CREATOR'", "if (mode === 'look' && typeof window.hqLook === 'function')", "return { race: 'homosapien', gender: lk.gender, appearance: lk.appearance };", "btn('look', 'YOUR OWN LOOK'", 'data-fn="_mountReactCreator"', 'window._hqRefreshAvatar = function ()']) assert.ok(mp.includes(s), 'map.js has ' + s);
    for (const s of ['getRace3DModel(race, gender, spec.appearance || undefined)', 'if (spec.appearance && def && def.creatorBase) unit.appearance = spec.appearance;', 'appearance: av.appearance || null', 'snapshot: function (opts)', "v.canvas.toDataURL('image/jpeg', q)"]) assert.ok(renderer.includes(s), 'three-renderer has ' + s);
    for (const s of ["const look = (typeof window.hqLook === 'function') ? window.hqLook(profile) : null;", "return { race: 'your own look', url: look.portrait, look: true };", "className: portrait.look ? 'door-photo-look' : undefined"]) assert.ok(pf.includes(s), 'profile.js has ' + s);
    for (const s of ['function CreatorControls({ appearance, gender, disabled, onChange, footer, name, onName, onLoad })', 'function OfficerCreator()', 'window._mountReactCreator = function ()', 'window._unmountReactCreator = function ()', "window.EWCharViewer.snapshot({ w: 256, h: 320 })", "window.hqSetAvatar(profile, 'look')", "'USE YOUR OWN LOOK'"]) assert.ok(pb.includes(s), 'party-builder has ' + s);
    assert.ok(ih.includes('<div id="creatorOverlay"></div>'), 'index.html hosts the mirror');
    assert.ok(css.includes('.pb-officer') && css.includes('.door-photo-look'), 'css has the mirror sheet and the photo');
    // the two screens render headlessly with React (skipped without react + react-dom)
    let React, ReactDOMServer;
    try { React = require('react'); ReactDOMServer = require('react-dom/server'); } catch (_) { return; }
    const win = Object.assign({}, context.window, {
        React, ReactDOM: { createRoot: () => ({ render() {}, unmount() {} }) },
        normalizeCharacterAppearance: normalize, randomCharacterAppearance: context.randomCharacterAppearance,
        ProfileSystem: { getActiveProfileIndex: () => 0, loadProfile: () => ({ username: 'probe', door: { hq: {} } }), saveProfile: () => {}, getActiveProfile: () => ({ username: 'probe', door: { hq: {} } }) },
        hqLook: (p) => (p && p.door && p.door.hq && p.door.hq.look) || null,
        addEventListener() {}, removeEventListener() {}, localStorage: { getItem: () => null, setItem() {} },
        location: { search: '' }, navigator: { userAgent: '' }, matchMedia: () => ({ matches: false, addEventListener() {} }),
    });
    win.window = win; win.self = win;
    const el = () => ({ style: {}, setAttribute() {}, appendChild() {}, classList: { add() {}, remove() {} }, textContent: '' });
    Object.assign(win, { document: { addEventListener() {}, removeEventListener() {}, getElementById: () => null, createElement: el, head: el(), body: el(), querySelector: () => null, querySelectorAll: () => [] },
        console: { log() {}, warn() {}, error() {} }, setTimeout, clearTimeout, requestAnimationFrame: () => 0, cancelAnimationFrame() {}, performance, state: {}, getFactionColor: () => '#fff', getRaceLabel: r => r });
    vm.createContext(win);
    vm.runInContext(pb, win);
    const parts = win._ewCreatorParts;
    assert.ok(parts && parts.CreatorControls && parts.OfficerCreator, 'the parts are exposed for the tests');
    const h = React.createElement;
    const a = normalize({ outer: 'jacket', outerPattern: 'camo', topPattern: 'stripes', feet: 'boots', belt: 'belt', gloves: 'gloves' });
    const html = ReactDOMServer.renderToString(h(parts.CreatorControls, { appearance: a, gender: 'female', disabled: false, onChange: () => {}, footer: h('i', null, 'foot') }));
    const pats = context.window.EW_PATTERNS.length, layers = context.window.EW_APPEARANCE_LAYERS.filter(L => !L.extra || a[L.slot] !== 'none').length;   // rev 10: the extra layers only while worn
    assert.equal((html.match(/pb-pattern-tile/g) || []).length, pats * layers, 'every worn layer shows every print');
    assert.ok(/colour 2/.test(html) && /Outer layer/.test(html) && /<i>foot<\/i>/.test(html), 'colour 2 rows, the layer rows, the footer');
    const html2 = ReactDOMServer.renderToString(h(parts.OfficerCreator));
    for (const s of ['THE MIRROR', 'SAVE LOOK', 'PHOTO PENDING', 'TAKE PHOTO', 'pb-creator-controls', 'pb-officer-stage']) assert.ok(html2.includes(s), 'the mirror screen shows ' + s);
});

test('rev 9 — the details, the accessories, the loose cuts, the wrist limit, the cloth collision and the preview bake', () => {
    const block = renderer.slice(RENDER_BLOCK[0], RENDER_BLOCK[1]);
    const cc = {}; vm.runInContext(block.slice(block.indexOf('var CC_TANK_FRONT'), block.indexOf("/* The pack's hair diffuse")), vm.createContext(cc));
    // the catalogues grew on both sides
    for (const id of ['polo', 'henley']) assert.ok(cc.CC_TOPS[id] && cc.CC_TOPS[id].placket, id + ' is a top with a placket');
    for (const id of ['cardigan', 'hoodie', 'trench', 'parka']) assert.ok(cc.CC_OUTER[id] && cc.CC_OUTER[id].sleeveEase < cc.CC_OUTER[id].ease, id + ' is an outer layer with a tapered sleeve');
    for (const id of ['baggy', 'cargo', 'sweatpants']) assert.ok(cc.CC_BOTTOMS[id] && cc.CC_BOTTOMS[id].ease >= 0.014, id + ' is a loose cut');
    assert.ok(cc.CC_FEET.sandals && cc.CC_FEET.sandals.straps.length === 2, 'sandals wear two straps');
    assert.ok(cc.CC_OUTER.jacket.zipTape && cc.CC_OUTER.blazer.buttons && cc.CC_OUTER.coat.pockets.length && cc.CC_OUTER.trench.beltBand && cc.CC_OUTER.trench.buttons.double && cc.CC_OUTER.hoodie.pockets.length, 'the rows carry their details');   // rev 10: no collars / hoods any more
    assert.ok(cc.CC_BOTTOMS.cargo.pockets.some(pk => pk.side), 'cargo pockets sit on the thigh');
    const EN = context.window.EW_APPEARANCE_ENUMS;
    assert.deepEqual([...EN.neckwear], ['none', 'tie', 'bowtie']); assert.deepEqual([...EN.glasses], ['none', 'round', 'square', 'shades']);
    assert.ok(/^#[0-9a-f]{6}$/.test(normalize({}).tieColor) && /^#[0-9a-f]{6}$/.test(normalize({}).glassesColor), 'the accessories have colours');
    assert.equal(normalize({ glasses: 'monocle' }).glasses, 'none');
    // the engine sites
    for (const s of ['function buildDetails()', 'function surfaceAt(x, t, mode)', 'function ribbon(b, L, pts, w, th, gain, upOf, taperW, taperH)', 'function placeBox(b, L, c, U, V, W, hw, hh, hd, gain, owner)', 'function smoothPath(pts)',
        'function collideSkirt(part)', 'mesh.boneTransform(i, _colV)', 'part.legs = legBones', 'tick: function ()', 'v.appearanceRig.tick()', 'entry.appearanceRig.tick()', 'e.appearanceRig.tick()',
        'function _lqLimit(rest, q, lim)', 'def.wristLimit', 'wristPlane - A.past', 'past: past', "AA.past > -0.012 * Hm",
        'CC_FACE_PREVIEW_TEX', 'CC_SETTLE_MS', 'function update(value, opts)', "update(pend, { preview: true })", 'v.appearanceSettle', 'part.patPreview[which]',
        "name === 'trim'", "name === 'tie'", "name === 'glasses'", 'hemEase', 'layerEaseAtQ']) assert.ok(renderer.includes(s), 'renderer has ' + s);
    assert.ok(!/tail: \{ hem: 0\.40/.test(block), 'the coat has no lathe tail');
    assert.match(read('sprites.js'), /wristLimit: 30/);
    const pb = read('party-builder.js');
    for (const s of ['queueChange', "ccChoice('neckwear'", "ccChoice('glasses'", "ccColorRow('tieColor'", "ccColorRow('glassesColor'", 'EW_NECKWEAR_STYLES', 'EW_GLASSES_STYLES']) assert.ok(pb.includes(s), 'party-builder has ' + s);
    assert.ok(/type: 'color', value: appearance\[key\], 'aria-label': 'Custom ' \+ label, onChange: e => queueChange/.test(pb), 'the colour input coalesces per frame');
    assert.ok(read('creator-render.js').includes('trim|tie|glasses'), 'creator-render.js renders the new shells');
});

test('rev 10 — the locker, the name, topless, the extra layers, the eight prints, the beard styles, the foot frame, the patches (source + data)', () => {
    const W = context.window, EN = W.EW_APPEARANCE_ENUMS, block = renderer.slice(RENDER_BLOCK[0], RENDER_BLOCK[1]);
    // the data model
    const pats = W.EW_PATTERNS.map(p => p.id);
    for (const id of ['hpinstripe', 'hearts', 'minidots', 'diamonds', 'houndstooth', 'zebra', 'leopard', 'crosshatch']) assert.ok(pats.includes(id), 'print ' + id);
    assert.ok(pats.length >= 20 && new Set(pats).size === pats.length);
    assert.ok(EN.outfit.includes('none') && normalize({ outfit: 'none' }).outfit === 'none' && normalize({}).outfit === 'tee', 'topless is a choice, the tee the default');
    assert.deepEqual([...EN.beard], ['none', 'stubble', 'beard', 'goatee', 'moustache', 'fullbeard']);
    assert.deepEqual([...EN.outfit2], ['none'].concat(EN.outfit.filter(x => x !== 'none'))); assert.deepEqual([...EN.bottoms2], ['none'].concat(EN.bottoms));
    assert.equal(normalize({}).outfit2, 'none'); assert.equal(normalize({}).bottoms2, 'none'); assert.equal(normalize({ bottoms2: 'briefs' }).bottoms2, 'briefs'); assert.equal(normalize({ outfit2: 'none2' }).outfit2, 'none');
    const extras = W.EW_APPEARANCE_LAYERS.filter(L => L.extra);
    assert.equal(JSON.stringify(extras.map(L => [L.id, L.slot])), JSON.stringify([['top2', 'outfit2'], ['bottom2', 'bottoms2']]));   // (cross-realm: compare by content)
    for (const L of W.EW_APPEARANCE_LAYERS) { assert.ok(L.slot && EN[L.slot], L.id + ' names its style slot'); assert.ok(EN[L.fabric] && EN[L.pattern] && /^#[0-9a-f]{6}$/.test(normalize({})[L.color]) && /^#[0-9a-f]{6}$/.test(normalize({})[L.color2]), L.id + ' keys'); }
    // an unworn extra layer warms nothing; a worn one warms its fabric
    const base = { hair: 'bald', topFabric: 'plain', bottomFabric: 'plain', outerFabric: 'plain', feetFabric: 'plain', glovesFabric: 'plain', beltFabric: 'plain', top2Fabric: 'wool', bottom2Fabric: 'silk' };
    assert.equal(W.getCharacterAppearanceAssets(base).fabrics.length, 0);
    assert.deepEqual([...W.getCharacterAppearanceAssets(Object.assign({ outfit2: 'tank', bottoms2: 'briefs' }, base)).fabrics], [W.getFabricTextureUrl('wool'), W.getFabricTextureUrl('silk')]);
    // the renderer
    const cc = {}; vm.runInContext(block.slice(block.indexOf('var CC_TANK_FRONT'), block.indexOf("/* The pack's hair diffuse")), vm.createContext(cc));
    assert.ok(!Object.values(cc.CC_TOPS).some(T => T.collar) && !Object.values(cc.CC_OUTER).some(T => T.collar), 'no collar / hood rows');
    assert.ok(!/A COLLAR — a band standing up/.test(block) && !block.includes("T.collar === 'hood'"), 'the collar ribbon is gone');
    assert.ok(cc._ccTopDef('none') === null && cc._ccTopDef('tee') === cc.CC_TOPS.tee, 'topless has no cut');
    assert.ok(typeof cc._ccOverDef === 'function' && cc._ccOverDef(cc.CC_BOTTOMS.briefs, 0.007).ease > cc.CC_BOTTOMS.briefs.ease, 'an extra layer rides at a larger ease');
    for (const s of ['function surfacePatch(b, L, cx, t, hw, hh, mode, th, gain, opts)', "if (qt < 0.15) return qx >= 0 ? 5 : 6", 'var _armRegX = 0.155', '_armRegX = part.shoulder.x + 0.012', "limbs['foot' + sd] = polyline(", 'Ft.uOff = uvL[0] - uvF[0]',
        'ANG = new Float32Array(N), TURN = new Float32Array(N)', 'if (amax - amin > Math.PI)', "var TOP2 = a.outfit2 && a.outfit2 !== 'none'", "var BOT2 = a.bottoms2 && a.bottoms2 !== 'none'", "{ name: 'top2'", "{ name: 'bottom2'", "top2: shell('top2'", "bottom2: shell('bottom2'",
        'var bPush = bStyle', 'surfaceNormals(P, ids, NB, weld, RC);\n                smoothNormals(NB, part, 3, bodyNormalWeight);\n            }', "beardStyle === 'moustache'", "beardStyle === 'fullbeard'", 'var strand = Math.pow(', 'var NTH = 96', 'UNDER = (opts.under || [])', 'if (RAD[o7] < map[o7] + 0.0005 * H)',
        'THE BOW (rev 10)', 'var covered = (L.name === \'bottom\'', "a.outfit2, a.bottoms2, a.beard].join('|')", "['top', 'bottom', 'outer', 'feet', 'gloves', 'belt', 'skirt', 'top2', 'bottom2'].forEach", "(which === 'feet' || which === 'gloves' || which === 'belt') ? 2 : 1", "top2: ['top2Fabric'", "margin = 0.011 * sc"]) assert.ok(block.includes(s), 'renderer block has ' + s);
    assert.ok(!block.includes('function limbProfile('), 'u stays at one radius per limb (the skin-radius u fanned the stripes)');
    // the builder, the css, the profile
    const pb = read('party-builder.js'), css = read('styles-base.css'), dj = read('data.js');
    for (const s of ['function SavedLooks({ name, gender, appearance, disabled, onName, onLoad })', "const PB_LOOKS_KEY = 'ew_saved_looks'", 'function pbLooksLoad()', 'function pbLooksSave(name, gender, appearance)', 'function pbLooksDelete(id)', 'window._ewSavedLooks =', "'💾 SAVE CHARACTER'", 'h(SavedLooks, { name: name ||',
        "' ADD LAYER'", 'const ccExtraLayers = ()', "'✕ REMOVE'", "['moustache', 'Moustache']", "['fullbeard', 'Full beard']", "appearance.outfit !== 'none' ? ccFabricTiles('topFabric', 'Top')", 'name: unitName, onName: (v) => { handleNameChange(v); refresh(); }', "onLoad: (e) => { changeAppearance(e.appearance, e.gender); handleNameChange(e.name); refresh(); }",
        'const [lookName, setLookName]', 'portrait: url, name: lookName']) assert.ok(pb.includes(s), 'party-builder has ' + s);
    for (const s of ['.pb-looks', '.pb-look-chip', '.pb-creator-name', '.pb-cc-add-btn', '.pb-layer-remove']) assert.ok(css.includes(s), 'css has ' + s);
    assert.ok(dj.includes("name: typeof rec.name === 'string' ? rec.name.slice(0, 24) : ''") && dj.includes("name: typeof look.name === 'string' ? look.name.trim().slice(0, 24) : ''"), 'the officer look carries a name');
    assert.ok(read('creator-render.js').includes('top2|bottom2|top|bottom'), 'creator-render.js renders the extra layers');
    // the locker in a sandbox with a fake localStorage
    const store = {}, win = { localStorage: { getItem: k => (k in store ? store[k] : null), setItem: (k, v) => { store[k] = String(v); }, removeItem: k => { delete store[k]; } }, normalizeCharacterAppearance: normalize, Date, JSON, Math, String, Array, Object, Number, console };
    win.window = win; vm.createContext(win);
    vm.runInContext(pb.slice(pb.indexOf("const PB_LOOKS_KEY = 'ew_saved_looks'"), pb.indexOf('/* the NAME field + the locker')), win);
    assert.equal(win.pbLooksLoad().length, 0);
    const e1 = win.pbLooksSave('  Ada ', 'female', { outfit: 'gown', bottoms2: 'briefs', topColor: '#ABCDEF' });
    assert.ok(e1 && e1.name === 'Ada' && e1.gender === 'female' && e1.appearance.outfit === 'gown' && e1.appearance.bottoms2 === 'briefs' && e1.appearance.topColor === '#abcdef', 'saved sanitized');
    win.pbLooksSave('Bob', 'male', {}); win.pbLooksSave('ada', 'male', { outfit: 'tee' });
    const list = win.pbLooksLoad();
    assert.equal(JSON.stringify(list.map(e => e.name)), JSON.stringify(['ada', 'Bob']), 'the same name (case-insensitive) overwrites, newest first');
    assert.equal(list[0].gender, 'male');
    assert.equal(JSON.stringify(win.pbLooksDelete(list[1].id).map(e => e.name)), JSON.stringify(['ada']));
    store['ew_saved_looks'] = '{"not":"an array"}'; assert.equal(win.pbLooksLoad().length, 0, 'a bad store reads as empty');
    store['ew_saved_looks'] = 'garbage'; assert.equal(win.pbLooksLoad().length, 0);
});

test('rev 10 — topless, the extra layers and the beard on the real rig', { skip: !THREE || !haveModels }, async () => {
    const c = { THREE, console, TextDecoder, URL, Blob, setTimeout, clearTimeout, performance, normalizeCharacterAppearance: normalize,
        getHairStyleUrl: () => null, getFabricTextureUrl: context.window.getFabricTextureUrl, getCharacterAppearanceAssets: context.window.getCharacterAppearanceAssets,
        getCharacterModelFallback: context.getCharacterModelFallback, EW_FABRICS: context.window.EW_FABRICS, _unitGlbCache: {} };
    c.self = c; c.window = c; c._loadUnitGLB = () => {};
    vm.createContext(c);
    vm.runInContext(fs.readFileSync(require.resolve('three/examples/js/loaders/GLTFLoader.js'), 'utf8'), c);
    vm.runInContext(fs.readFileSync(require.resolve('three/examples/js/utils/SkeletonUtils.js'), 'utf8'), c);
    vm.runInContext(renderer.slice(renderer.indexOf('    /* ══════════════════════════════════════════════════════════════════\n     *  CHARACTER CREATOR RUNTIME'), RENDER_BLOCK[1]), c);
    const origLoad = THREE.TextureLoader.prototype.load;
    THREE.TextureLoader.prototype.load = function (url, onLoad) { const t = new THREE.Texture(); if (onLoad) setTimeout(() => onLoad(t), 0); return t; };
    const load = f => new Promise((ok, fail) => { const b = fs.readFileSync(f); new THREE.GLTFLoader().parse(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength), '', ok, fail); });
    try {
        const gltf = await load(path.join(CC, 'Meshy_AI_human_body_base_mesh_male_rigged.glb'));
        const clone = THREE.SkeletonUtils.clone(gltf.scene);
        const rig = c._createAppearanceRig(clone, { hair: 'bald' }, true);
        const shellOf = nm => { let out = null; clone.traverse(n => { if (n.name === 'EWCreator_' + nm) out = n; }); return out; };
        const count = nm => shellOf(nm).geometry.index.count, finite = nm => Array.from(shellOf(nm).geometry.attributes.position.array).every(Number.isFinite);
        const body = () => { let b = null; clone.traverse(n => { if (n.isSkinnedMesh && !/EWCreator/.test(n.name)) b = n; }); return b; };
        rig.update({ hair: 'bald', outfit: 'none', neckwear: 'bowtie' });
        assert.equal(count('top'), 0, 'topless draws no top'); assert.ok(body().geometry.index.count > 0 && count('tie') > 0 && count('trim') > 0, 'the skin shows, the bow sits on it');
        rig.update({ hair: 'bald', outfit: 'suit', outfit2: 'tank', bottoms: 'trousers', bottoms2: 'briefs', belt: 'belt' });
        assert.ok(count('top') > 0 && count('top2') > 0 && count('bottom') > 0 && count('bottom2') > 0 && count('belt') > 0, 'both extra layers draw over their base layers');
        assert.ok(finite('top2') && finite('bottom2'));
        assert.ok(shellOf('top2').visible && shellOf('bottom2').visible);
        rig.update({ hair: 'bald', outfit: 'tee', bottoms: 'trousers', bottoms2: 'skirt' });
        assert.ok(count('skirt') > 0 && count('bottom') > 0 && count('bottom2') === 0, 'a skirt worn over is the lathe (the trousers stay), no cut bottom2 shell');
        rig.update({ hair: 'bald', outfit: 'none', outfit2: 'none', bottoms2: 'none' });
        assert.ok(count('top2') === 0 && count('bottom2') === 0 && !shellOf('top2').visible, 'unworn extras hide');
        // the beard has volume: the chin's front moves out between clean and full beard
        const chinZ = () => { const b = body(), P = b.geometry.attributes.position, bb = new THREE.Box3().setFromBufferAttribute(P), H = bb.max.y - bb.min.y; let best = -1e9; for (let i = 0; i < P.count; i++) { const t = (P.getY(i) - bb.min.y) / H; if (t > 0.872 && t < 0.885 && Math.abs(P.getX(i)) < 0.01 * H && P.getZ(i) > best) best = P.getZ(i); } return best; };
        rig.update({ hair: 'bald', outfit: 'tee', beard: 'none' }); const z0 = chinZ();
        rig.update({ hair: 'bald', outfit: 'tee', beard: 'fullbeard' }); const z1 = chinZ();
        assert.ok(z1 - z0 > 0.003 && z1 - z0 < 0.012, 'a full beard stands the chin out 4–8 mm (' + (z1 - z0).toFixed(4) + ')');
        rig.update({ hair: 'bald', outfit: 'tee', beard: 'moustache' }); assert.ok(Math.abs(chinZ() - z0) < 1e-4, 'a moustache adds no chin');
        rig.dispose();
    } finally { THREE.TextureLoader.prototype.load = origLoad; }
});

test('rev 11 — the skirt hem: a smooth weight field, the collision at the bones\' scale, the rest depth, the skirt under an outer (source)', () => {
    const block = renderer.slice(RENDER_BLOCK[0], RENDER_BLOCK[1]);
    for (const s of ['THE SMOOTH WEIGHT FIELD', 'var roleOf = function (bi)', 'var fieldAt = function (r, th2, acc, w)', 'THE SCALE IS THE BONES', 'sc: lsc }', 'var along = (cum + t * len) / S.sc', 'THE REST DEPTH', 'part.skirtRest = ', 'if (REST) best -= REST[i] * sc;', 'THE TENT', 'part.skirtGrid = { rows: rows, cols: cols', 'var overLim = function (r, c)', 'overLathe: tailField, grid: true', 'qt > 0.45 || qt < 0.06', 'if (firstLeg > 0) for (k = 0; k < firstLeg; k++) r[k] = r[firstLeg];'])
        assert.ok(block.includes(s), 'renderer block has ' + s);
    assert.ok(!/blendSkin\(ri, mirror, wMirror\)/.test(block), 'the lathe no longer rides one rep vertex per column');
    assert.ok(!/sc = _colT\.setFromMatrixColumn\(mw, 0\)\.length\(\)/.test(block), 'the capsule scale is no longer the mesh node\'s');
    assert.ok(/var tailField = \(OUT && OUT\.tail\) \? buildLathe\(/.test(block) && block.indexOf('var tailField') < block.indexOf('if (dress) buildLathe('), 'the coat tail is built before the skirt so the skirt can hang inside it');
    assert.ok(read('creator-render.js').includes("const POSE = process.env.POSE || 'bind'"), 'creator-render.js renders posed');
});

test('rev 11 — the posed hem on the real rig: no sawtooth, the bind pose untouched, the collision pushes the knee out', { skip: !THREE || !haveModels }, async () => {
    const c = { THREE, console, TextDecoder, URL, Blob, setTimeout, clearTimeout, performance, normalizeCharacterAppearance: normalize,
        getHairStyleUrl: () => null, getFabricTextureUrl: context.window.getFabricTextureUrl, getCharacterAppearanceAssets: context.window.getCharacterAppearanceAssets,
        getCharacterModelFallback: context.getCharacterModelFallback, EW_FABRICS: context.window.EW_FABRICS, _unitGlbCache: {} };
    c.self = c; c.window = c; c._loadUnitGLB = () => {};
    vm.createContext(c);
    vm.runInContext(fs.readFileSync(require.resolve('three/examples/js/loaders/GLTFLoader.js'), 'utf8'), c);
    vm.runInContext(fs.readFileSync(require.resolve('three/examples/js/utils/SkeletonUtils.js'), 'utf8'), c);
    vm.runInContext(renderer.slice(renderer.indexOf('    /* ══════════════════════════════════════════════════════════════════\n     *  CHARACTER CREATOR RUNTIME'), RENDER_BLOCK[1]), c);
    const origLoad = THREE.TextureLoader.prototype.load;
    THREE.TextureLoader.prototype.load = function (url, onLoad) { const t = new THREE.Texture(); if (onLoad) setTimeout(() => onLoad(t), 0); return t; };
    const load = f => new Promise((ok, fail) => { const b = fs.readFileSync(f); new THREE.GLTFLoader().parse(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength), '', ok, fail); });
    try {
        const gltf = await load(path.join(CC, 'Meshy_AI_human_body_base_mesh_female_rigged.glb'));
        const hem = (pose) => {
            const clone = THREE.SkeletonUtils.clone(gltf.scene), rig = c._createAppearanceRig(clone, { hair: 'bald', outfit: 'tee', bottoms: 'skirt', outer: 'jacket' }, true);
            const bone = n => { let b = null; clone.traverse(o => { if (o.isBone && o.name === n) b = o; }); return b; };
            for (const [n, a] of pose) bone(n).rotateX(a);
            clone.updateMatrixWorld(true);
            let sk; clone.traverse(n => { if (n.isSkinnedMesh && n.name === 'EWCreator_skirt') sk = n; });
            sk.skeleton.update();
            const pre = new Float32Array(sk.geometry.attributes.position.array);
            rig.tick();
            const A = sk.geometry.attributes.position.array; let moved = 0; for (let i = 0; i < A.length; i += 3) if (Math.hypot(A[i] - pre[i], A[i + 1] - pre[i + 1], A[i + 2] - pre[i + 2]) > 1e-6) moved++;
            sk.skeleton.update();
            const v = new THREE.Vector3(), cols = 97, rows = Math.floor(sk.geometry.attributes.position.count / cols), Y = [];
            for (let cc = 0; cc < cols; cc++) { sk.boneTransform((rows - 1) * cols + cc, v); v.applyMatrix4(sk.matrixWorld); Y.push(v.y); }
            let s2 = 0, mx = 0; for (let cc = 1; cc + 1 < cols; cc++) { const y2 = Math.abs(Y[cc - 1] - 2 * Y[cc] + Y[cc + 1]); s2 += y2; mx = Math.max(mx, y2); }
            rig.dispose();
            return { mean: s2 / (cols - 2), max: mx, moved };
        };
        const bind = hem([]), walk = hem([['LeftUpLeg', 0.55], ['RightUpLeg', -0.35], ['LeftLeg', 0.35]]), kick = hem([['LeftUpLeg', 1.0], ['RightUpLeg', -0.2]]);
        assert.equal(bind.moved, 0, 'the bind pose is left exactly as built (the rest depth)');
        assert.ok(bind.mean < 0.0002, 'bind hem flat');
        assert.ok(walk.mean < 0.0025, 'walk hem mean |Δ²y| ' + (walk.mean * 1000).toFixed(2) + ' mm (the rev 10 lathe: 5.4 mm)');
        assert.ok(walk.max < 0.04, 'walk hem max |Δ²y| ' + (walk.max * 1000).toFixed(1) + ' mm (the rev 10 lathe: 156 mm)');
        assert.ok(walk.moved > 50 && kick.moved > walk.moved, 'the collision pushes the leg out (' + walk.moved + ' / ' + kick.moved + ' vertices)');
    } finally { THREE.TextureLoader.prototype.load = origLoad; }
});
