'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(process.env.EW_EFFECT_SOURCE||__dirname,'three-vfx-effects.js'),'utf8');
function section(a,b){const i=source.indexOf(a),j=source.indexOf(b,i+a.length);assert.ok(i>=0&&j>i);return source.slice(i,j);}
function harness(){
 let now=0,off=false,suppressed=false,particles=true;const timers=[],events=[];
 const record=name=>(...args)=>events.push({name,at:now,args:JSON.parse(JSON.stringify(args))});
 const post={spellGrade:record('grade'),spellGradeKick:record('kick'),bloomPulse:record('bloom')};
 const ctx=vm.createContext({Set,Array,Math,window:{setTimeout(fn,ms){timers.push({fn,at:now+ms,canceled:false,ran:false});return timers.length;},clearTimeout(id){timers[id-1].canceled=true;}},_catOff:()=>off,_suppressed:()=>suppressed,_canSpawn:()=>particles&&!suppressed,_cfg:()=>({tileSize:100}),_worldPos:(x,y)=>({x:x*100,y:20,z:y*100}),tilePx:(x,y)=>({x:x*100,y:y*100}),unitSurfaceZ:()=>20,rn:(a,b)=>(a+b)/2,_post:()=>post,_spawn:record('particle'),_SIG_SPECTRUM:[1,2,3,4,5,6,7],_SIG_SPECTRUM_SPRITES:['a','b','c']});
 for(const name of ['PsychedelicTint','Kaleidoscope3D','FractalTunnel3D','OrbBurst3D','ChargeSpiral3D','SpectrumBurst3D','ScreenFlash','Shake','MagicCircle3D','ShockRing3D'])ctx['_sig'+name]=record(name);
 vm.runInContext(section('    var _fxLifetime','    function rn')+section('    function _sigEgoDeath3D(','    /* ── MERKABA'),ctx);
 return {events,timers,ctx,fire(kind,opts={}){ctx[kind==='ego'?'_sigEgoDeath3D':'_sigTimeRewind3D'](2,3,opts);},retire(){ctx._fxCancelDelays();},disable(){off=true;},suppress(){suppressed=true;},noParticles(){particles=false;},advance(to){for(;;){const t=timers.filter(t=>!t.ran&&!t.canceled&&t.at<=to).sort((a,b)=>a.at-b.at)[0];if(!t)break;now=t.at;t.ran=true;t.fn();}now=to;}};
}
for(const kind of ['ego','rewind']){
 for(const at of [0,350,650])test(`${kind}: retirement at ${at} blocks stale callbacks after a new cast`,()=>{const h=harness();h.fire(kind);h.advance(at);const pending=h.timers.filter(t=>!t.ran);assert.ok(pending.length);h.retire();assert.ok(pending.every(t=>t.canceled));assert.equal(h.ctx._fxDelays.size,0);h.fire(kind);const count=h.events.length;pending.forEach(t=>t.fn());assert.equal(h.events.length,count);h.advance(4000);assert.ok(h.events.length>count);assert.equal(h.ctx._fxDelays.size,0);});
 for(const block of ['disable','suppress'])test(`${kind}: ${block} gates initial and delayed effects`,()=>{const h=harness();h[block]();h.fire(kind);assert.equal(h.events.length,0);assert.equal(h.timers.length,0);const live=harness();live.fire(kind);const count=live.events.length;live[block]();live.advance(4000);assert.equal(live.events.length,count);assert.equal(live.ctx._fxDelays.size,0);});
 test(`${kind}: particle budget leaves scheduled geometry and screen effects intact`,()=>{const h=harness();h.noParticles();h.fire(kind);h.advance(4000);assert.equal(h.events.filter(e=>e.name==='particle').length,0);assert.ok(h.events.some(e=>e.name==='ScreenFlash'));assert.ok(h.events.some(e=>e.name==='OrbBurst3D'&&e.args[2].mode==='out'));assert.equal(h.ctx._fxDelays.size,0);});
}
test('Ego Death preserves custom implosion timing, inward spectrum and outward white burst',()=>{const h=harness();h.fire('ego',{implodeMs:1200});assert.deepEqual(h.timers.map(t=>t.at),[300,1200]);h.advance(299);assert.equal(h.events.filter(e=>e.name==='particle').length,0);h.advance(300);const inward=h.events.filter(e=>e.name==='particle');assert.equal(inward.length,21);assert.ok(inward.every(e=>e.args[0].seek.spiralDeg===-260));assert.deepEqual(inward.slice(0,7).map(e=>e.args[0].tint),[1,2,3,4,5,6,7]);h.advance(1200);assert.equal(h.events.filter(e=>e.name==='particle').length,45);assert.equal(h.events.filter(e=>e.name==='SpectrumBurst3D').length,1);assert.deepEqual(h.events.find(e=>e.name==='kick').args,[14,280]);h.advance(4000);assert.equal(h.events.filter(e=>e.name==='particle').length,45);assert.equal(h.ctx._fxDelays.size,0);});
test('Time Rewind preserves kick, ghost and release timing with custom duration',()=>{const h=harness();h.fire('rewind',{ms:1000});assert.equal(h.events.filter(e=>e.name==='particle').length,26);h.advance(640);assert.deepEqual(h.events.filter(e=>e.name==='kick').map(e=>[e.at,...e.args]),[[0,8,140],[300,10,160],[640,12,200]]);assert.deepEqual(h.events.filter(e=>e.name==='particle'&&e.args[0].mode==='y-locked').map(e=>e.at),[0,150,300,450]);assert.deepEqual(h.events.filter(e=>e.name==='ShockRing3D').map(e=>e.at),[550]);assert.equal(h.ctx._fxDelays.size,0);});
