'use strict';
// Production lifetime, animation and spear construction; rendering is doubled.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(process.env.EW_EFFECT_SOURCE||__dirname,'three-vfx-effects.js'),'utf8');
function section(a,b){const i=source.indexOf(a),j=source.indexOf(b,i+a.length);assert.ok(i>=0&&j>i,a);return source.slice(i,j);}
function harness({cap=50,missing=false,vanish=false}={}){
 const timers=[],events=[],frames=[],resources=[],warnings=[];let now=0,suppressed=false,reads=0;
 class Vector{constructor(x=0,y=0,z=0){this.set(x,y,z);}set(x,y,z){Object.assign(this,{x,y,z});return this;}setScalar(v){return this.set(v,v,v);}}
 class Resource{constructor(opts){Object.assign(this,opts);this.disposals=0;resources.push(this);}dispose(){this.disposals++;}}
 class Group{constructor(){this.children=[];this.position=new Vector();this.rotation=new Vector();this.scale=new Vector(1,1,1);}add(o){this.children.push(o);o.parent=this;}remove(o){this.children=this.children.filter(c=>c!==o);o.parent=null;}traverse(fn){fn(this);this.children.forEach(c=>c.traverse(fn));}}
 class Mesh extends Group{constructor(geometry,material){super();Object.assign(this,{geometry,material,isMesh:true,renderOrder:0});}}
 const scene=new Group(),texture={dispose(){throw Error('shared texture disposed');}};
 const record=name=>(...args)=>events.push({name,at:now,args:JSON.parse(JSON.stringify(args))});
 const ctx=vm.createContext({Set,Array,Math,console:{warn:(...args)=>warnings.push(args)},performance:{now:()=>now},window:{setTimeout(fn,ms){timers.push({fn,ms,at:now+ms,canceled:false,ran:false});return timers.length;},clearTimeout(id){timers[id-1].canceled=true;}},THREE:{Group,Mesh,SphereGeometry:Resource,CylinderGeometry:Resource,ConeGeometry:Resource,PlaneGeometry:Resource,MeshBasicMaterial:Resource,Color:class{}},_getVFXScene:()=>missing||(vanish&&++reads>1)?null:scene,_worldPos:(x,y)=>({x:x*100,y:20,z:y*100,ts:100}),_cfg:()=>({tileSize:100}),_suppressed:()=>suppressed,_sigMat:(color,opts)=>Object.assign(new Resource(),{color},opts),_sigGlyphBandTex:()=>texture,_sigGlowTex:()=>texture,_sigTerrainTex:()=>texture,_sigCss:c=>'#'+c.toString(16).padStart(6,'0'),_sigActive:0,_SIG_MAX_ACTIVE:cap,_sigEntries:[],_fxSchedule:fn=>frames.push(fn),_sigEaseOutCubic:t=>1-(1-t)**3,_sigEaseInCubic:t=>t**3,_sigClamp01:t=>Math.max(0,Math.min(1,t)),_sigScreenFlash:record('flash'),_sigSpeedLinesFx:record('lines'),_sigSpeedBurst3D:record('burst'),_sigShockRing3D:record('ring'),_sigShake:record('shake'),_sigSparks:record('sparks'),_sigMagicCircle3D:record('circle')});
 vm.runInContext(section('    var _fxLifetime','    function rn')+section('    function _sigRun(','    /* full-viewport')+section('    function _sigWhiteout3D(','    /* ── horizontal scripture')+section('    function _sigRuneSphere3D(','    /* ── AURORA CURTAIN'),ctx);
 return {ctx,timers,events,scene,resources,warnings,
 fire(kind,opts={}){return ctx[{whiteout:'_sigWhiteout3D',rune:'_sigRuneSphere3D',prison:'_sigSpearPrison3D',gas:'_sigGasCloud3D'}[kind]](2,3,opts);},
 advance(ms){for(;;){const t=timers.filter(t=>!t.ran&&!t.canceled&&t.at<=ms).sort((a,b)=>a.at-b.at)[0];if(!t)break;now=t.at;t.ran=true;t.fn();}now=ms;},
 tick(ms){now=ms;frames.forEach(fn=>fn());assert.deepEqual(warnings,[]);},
 retire(){ctx._fxCancelDelays();[...ctx._sigEntries].forEach(e=>e.finish());},suppress(){suppressed=true;}
 };
}
for(const kind of ['whiteout','prison','gas']){
 test(`${kind} cancels pending emissions`,()=>{const h=harness();h.fire(kind);assert.ok(h.timers.length);h.retire();assert.ok(h.timers.every(t=>t.canceled));});
 test(`${kind} queued callbacks stay inert after a new cast`,()=>{const h=harness();h.fire(kind);const old=[...h.timers];h.retire();h.fire(kind);const before=[h.events.length,h.resources.length,h.timers.length];old.forEach(t=>t.fn());assert.deepEqual([h.events.length,h.resources.length,h.timers.length],before);});
 test(`${kind} suppression blocks delayed work`,()=>{const h=harness();h.fire(kind);const before=[h.events.length,h.resources.length];h.suppress();h.advance(3000);assert.deepEqual([h.events.length,h.resources.length],before);h.retire();});
}
test('whiteout keeps initial cues, custom payload and 90 ms second ring',()=>{const h=harness();h.fire('whiteout',{color:0x123456,ms:310,peak:.2,sizeTiles:2,shake:'soft',sparkSprite:'ice'});assert.equal(h.events.length,6);assert.deepEqual(h.events[0].args,['#123456',310,.2]);assert.equal(h.events.find(e=>e.name==='burst').args[2].size,200);assert.equal(h.events.find(e=>e.name==='sparks').args[2],'ice');h.advance(89);assert.equal(h.events.length,6);h.advance(90);assert.deepEqual(h.events.at(-1),{name:'ring',at:90,args:[2,3,{color:0x123456,r1:170,ms:380,height:50}]});assert.equal(h.ctx._fxDelays.size,0);});
for(const mode of ['cap','vanish'])test(`rune sphere disposes refused allocations on ${mode}`,()=>{const h=harness(mode==='cap'?{cap:0}:{vanish:true});assert.equal(h.fire('rune'),null);assert.equal(h.resources.length,6);assert.ok(h.resources.every(r=>r.disposals===1));assert.equal(h.scene.children.length,0);assert.equal(h.ctx._sigActive,0);h.retire();assert.ok(h.resources.every(r=>r.disposals===1));});
test('rune sphere returns its live entry, animates options and completes once',()=>{const h=harness();const e=h.fire('rune',{holdMs:100,radiusTiles:1.2,spin:.003,color:0x123456,runeColor:0xaabbcc});assert.equal(e.group,h.scene.children[0]);h.tick(200);const [shell,a,b]=e.group.children;assert.equal(shell.material.opacity,.14);assert.ok(shell.scale.x>120);assert.equal(a.material.color,0xaabbcc);assert.equal(a.rotation.y,.6);assert.ok(Math.abs(b.rotation.y+.9)<1e-12);h.tick(620);e.finish();h.retire();h.tick(700);assert.equal(h.scene.children.length,0);assert.ok(h.resources.every(r=>r.disposals===1));});
test('rune early retirement rejects old animation ticks without double disposal',()=>{const h=harness();const e=h.fire('rune');h.tick(100);h.retire();const scale=e.group.children[0].scale.x;h.tick(300);e.finish();assert.equal(e.group.children[0].scale.x,scale);assert.ok(h.resources.every(r=>r.disposals===1));});
for(const kind of ['rune','prison','gas'])test(`${kind} missing scene allocates and schedules nothing`,()=>{const h=harness({missing:true});h.fire(kind);assert.equal(h.resources.length,0);assert.equal(h.timers.length,0);assert.equal(h.events.length,0);});
test('prison keeps thrust beats and custom finisher followed by nested whiteout ring',()=>{const h=harness();h.fire('prison',{count:2,holdMs:200,finisherColor:0x123456,finisherPeak:.2,sparkSprite:'ice'});assert.equal(h.timers[0].ms,550);h.tick(350);assert.equal(h.events.filter(e=>e.name==='sparks').length,1);h.tick(440);assert.equal(h.events.filter(e=>e.name==='sparks').length,2);h.advance(550);assert.deepEqual(h.events.find(e=>e.name==='flash'&&e.at===550).args,['#123456',480,.2]);h.advance(640);assert.equal(h.events.filter(e=>e.name==='ring').length,2);h.tick(960);assert.equal(h.scene.children.length,0);assert.ok(h.resources.every(r=>r.disposals>=1));});
test('prison retirement between finisher and second ring cancels nested work',()=>{const h=harness();h.fire('prison');h.advance(1051);const pending=h.timers.filter(t=>!t.ran);assert.equal(pending.length,1);h.retire();h.fire('prison');const before=[h.events.length,h.resources.length,h.timers.length];pending.forEach(t=>t.fn());assert.deepEqual([h.events.length,h.resources.length,h.timers.length],before);});
test('prison finisher false keeps geometry without any timer',()=>{const h=harness();h.fire('prison',{finisher:false});assert.equal(h.timers.length,0);assert.equal(h.scene.children.length,2);h.retire();assert.ok(h.resources.every(r=>r.disposals>=1));});
test('prison cap refusal also cleans transitive rune sphere',()=>{const h=harness({cap:0});h.fire('prison',{finisher:false});assert.equal(h.scene.children.length,0);assert.ok(h.resources.every(r=>r.disposals>=1));});
test('gas retains stagger, gentle option, colors and normal animation cleanup',()=>{const h=harness();h.fire('gas',{count:6,ms:1000,color:0x123456,coreColor:0xabcdef,gentle:true});assert.deepEqual(h.timers.map(t=>t.ms),[0,80,160,240,320,0]);assert.equal(h.events.filter(e=>e.name==='sparks').length,0);h.advance(0);assert.equal(h.scene.children.length,2);assert.equal(h.scene.children[0].children[0].material.color,0xabcdef);assert.equal(h.scene.children[1].children[0].material.color,0x123456);h.advance(320);assert.equal(h.scene.children.length,6);h.tick(400);assert.ok(h.scene.children.every(g=>g.children[0].material.opacity>0));h.tick(1400);assert.equal(h.scene.children.length,0);assert.ok(h.resources.every(r=>r.disposals===1));});
test('gas partial emission retires puffs and prevents remaining allocation in a new cast',()=>{const h=harness();h.fire('gas');h.advance(80);assert.equal(h.scene.children.length,6);const pending=h.timers.filter(t=>!t.ran);const allocated=[...h.resources];h.retire();assert.ok(allocated.every(r=>r.disposals===1));h.fire('gas');const before=[h.resources.length,h.events.length];pending.forEach(t=>t.fn());assert.deepEqual([h.resources.length,h.events.length],before);h.advance(3000);h.retire();assert.ok(h.resources.every(r=>r.disposals===1));});
test('gas cap refusal disposes every delayed puff without touching textures',()=>{const h=harness({cap:0});h.fire('gas');h.advance(320);assert.equal(h.resources.length,24);assert.equal(h.scene.children.length,0);assert.ok(h.resources.every(r=>r.disposals===1));h.retire();assert.ok(h.resources.every(r=>r.disposals===1));});
